---
permalink: faq/faq-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: 本常見問題集可解答OnCommand Insight 有關「非正常現象偵測」的常見問題。 
---
= 異常偵測
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常見問題集可解答OnCommand Insight 有關「非正常現象偵測」的常見問題。



== 什麼是異常？

異常狀況是IOPS、延遲、使用率、緩衝區對緩衝區點數和CPU的效能變更事件、不符合先前觀察到的和預期的模式。OCI異常狀況偵測的目標是應用程式基礎架構服務應用程式、以尋找處理模式和行為的變更。這些週期性處理模式包括在營業時間和週末的工作負載效能中、有歷史的「退潮和流量」。OCI的異常偵測引擎使用機器學習情報來建立「正常」的基礎模式、並偵測定義的應用程式是否偏離預期行為。



== 異常偵測如何在OCI中運作？

OCI「異常偵測」是一種主動監控方法、利用機器學習情報、根據歷史資訊進行監控。其偵測新興效能異常狀況的能力遠低於傳統臨界值、可讓系統管理員在應用程式SLO或資料中心服務受到影響之前、有更多時間討論、規劃及減輕疑慮。

Insight會探索並自動對應整個基礎架構堆疊、以支援應用程式、從運算資源開始、透過交換器架構向下對應至儲存資源。OCI收集關鍵效能計數器、包括IOPS、延遲、節點資訊、儲存資源池使用率、Hypervisor CPU、 然後將每個資源的BB Credit Zero提供給異常偵測引擎、以供應用程式異常分析使用。異常結果每小時更新兩次、可在應用程式儀表板、應用程式登陸頁面及查詢表小工具上取得。異常評分會逐資源執行、並會針對整個應用程式基礎架構提供整體重要分數。



== 哪些OCI版本支援異常偵測？

OCI 7.2及更新版本支援異常偵測。



== OCI可為多少個應用程式啟用異常偵測？

OCI支援監控多達48個業務關鍵應用程式。



== 可以部署多少個異常偵測引擎（ADE）？

每個OCI作業伺服器一個異常偵測引擎。



== 如果我有48個以上的應用程式、是否可以部署其他異常偵測引擎？

是的、目前OCI支援每個OCI伺服器配對一個異常偵測引擎。在多個OCI伺服器環境中、可以「配對」的方式部署額外的異常偵測引擎和OCI作業伺服器。每部伺服器只有在啟用異常偵測功能的情況下、才能看到其應用程式。



== 應用程式叢集/群組的大小是否有擴充限制？

OCI工程部門使用Insight異常偵測功能、提供最佳操作與擴充的一般準則如下：每部Insight伺服器支援一個異常偵測引擎。OCI最多可監控48個應用程式。應用程式基礎架構最多可包含4000個物件。資源不足將會降低整體規模。



== 異常偵測需要哪些OCI授權？

異常偵測分析需要「探索」和「執行授權」。



== 開始偵測異常並查看結果需要多久時間？

啟用應用程式監控後、異常評分結果只要2-3小時就會出現。



== 我應該等多久才能操作結果？

異常狀況偵測引擎結果的品質和準確度會隨著時間（週、月、季等）而改善。週期性評估（週期性）通常會在第三週左右開始。對於時間長度較長的模式（例如每月）、引擎必須在調整異常分數之前觀察重複事件。



== 異常狀況偵測引擎會保留多久的學習時間？

異常狀況偵測引擎在儲存學習資訊的方式上、效率極高。統計學習可在數月內測量物件異常行為。Insight中的典型資料集並不像一般人所想像的那樣「資料」。異常狀況偵測引擎會根據時間來學習及儲存判定為「重大統計」的資料、並在必要時將不重要的資料取出。這種機制可大幅延長學習時間、同時減少儲存資料所需的資源和執行分析所需的時間



== 如果我今天啟用異常偵測、是否能告訴我上週發生了什麼異常？

否、當異常偵測初始化時、Insight伺服器會從Insight伺服器載入任何現有的效能資料、以提升異常偵測引擎對受監控應用程式及其基礎架構的瞭解程度。擷取的「預先存在的」效能資料將不會出現異常狀況。只有新的傳入資料會根據預先存在的資料進行分析時、才會報告異常狀況。新偵測到的異常情況將在幾小時內開始顯示。



== 異常分數如何計算？

每個應用程式異常分數都是根據各種個別資產分數的總和來計算。異常狀況偵測引擎運用30多種複雜演算法和公式來判斷異常狀況、並提供分數。使用者可以將這類分析評分技術與類似的醫療評分技術進行比較、例如「體內質量指數（BMI）」分數、其中包含許多變數和測量結果（重量、年齡、高度、密度等）。



== 每個藍色長條代表什麼？

每區塊3個長條圖代表一項資源及其異常意義範圍。藍色長條越多、觀察到的行為變化就越大。按一下區塊即可顯示（異常）、個別資源和計數器的重要性。



== 為什麼個別資源分數未加到總應用程式分數？

每個資源都會根據其在觀察到的行為上的差異而個別評分。個別資源評分的重要性在應用程式總評分中確實扮演著重要角色、但也可能包括其他分析和數學因素。



== 我可以設定異常偵測、以監控已指派附註的商業實體或物件嗎？

現在、只能在已定義的應用程式上啟用異常偵測。任何可指派給應用程式（VM、Hypervisor、伺服器、磁碟區和內部磁碟區）的物件、都可以進行群組和監控。



== OCI是否能提供高異常分數的通知？

是的、您可以根據應用程式的異常分數來建立應用程式效能原則。跨越原則中定義的臨界值會觸發警示、通知您應用程式中的資源相關問題。



== 當我關閉應用程式的異常偵測時、會發生什麼事？

應用程式基礎架構的所有已學習（歷史異常）資訊都會從異常偵測引擎中清除。所有異常偵測結果都會從Insight作業資料庫中清除。



== 何時應該使用靜態臨界值？

靜態臨界值非常適合用於最佳實務做法的基礎架構資源限制警示、以及識別事件持續時間。此外、它們也有助於管理服務層級、並針對各種錯誤計數器指標發出警示、例如連結重設、類別3捨棄和失去同步。



== 有哪些計畫可將其他指標納入異常狀況偵測？

隨著新的統計資料、使用者意見回饋和產品改善、Anomaly機器學習模式和演算法將會持續改善或調整。



== 資料倉儲（DWH）是否提供異常結果？

今天的異常結果不會傳送（ETL-ed）至OCI資料倉儲。使用者可在OCI應用程式登陸頁面或使用者定義的查詢表小工具中找到結果。
