---
permalink: faq/faq-general-insight-questions.html 
sidebar: sidebar 
keywords: redhat,Linux 
summary: 本常見問題集可解答OnCommand Insight 有關NetApp的常見問題。 
---
= 一般問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常見問題集可解答OnCommand Insight 有關NetApp的常見問題。



== 什麼時候OnCommand Insight 推出呢？

OCI是目前業界最成熟的基礎架構監控產品之一、目前已有十多年的積極開發經驗。以前稱為Onaro或SANscreen Isro, SANscreen 加入OnCommand 一套產品的時候改了這個功能的名稱,現在稱為OnCommand Insight 「Isro,」或「Insight」或「OCI」。



== 在我的環境中部署OCI需要多久時間？

OCI只是下載軟體而已。軟體安裝在兩部專用的虛擬或實體伺服器上。一般安裝只需2小時即可完成、庫存、容量與效能資料幾乎會立即開始提供。任何其他效能與最佳實務原則、使用者註釋及成本認知設定、都需要進行額外的規劃討論。



== OCI是否需要代理程式、收集器或探查？

OCI是100%無代理程式、不需要使用代理程式、點選或探查。所有裝置探索都是唯讀、頻外執行、以及透過IP執行。



== OCI如何探索及連線至裝置？

OCI設定運用資料中心環境中通常已存在的原生API和傳輸協定、不需要代理程式或探查。SSH、HTTP、SMIS和CLI只是幾個例子。如果裝置元件管理程式已經存在（例如EMC的Unaile）、OCI會與元件管理程式通訊、以擷取現有的環境資料。大多數的裝置探索僅需要IP位址和唯讀使用者名稱和密碼。這些設備發現可以是「一對多」、例如OCI的VMware資料來源。藉由探索VMware vCenter、OCI進而探索其所有ESXi主機及其相關VM、而且只需一個IP位址和認證即可。



== OCI是否需要專業服務？是否有、以及他們提供什麼服務？

對於中等規模的環境、我們建議使用專業服務進行部署、組態和整合、以及各種自訂報告和資料驗證的可能性。與OCI團隊和客戶互動經理進行簡短討論、有助於判斷哪些服務能為您帶來最大效益。



== OCI針對新功能與改善功能的更新頻率為何？

產品更新與Service Pack適用於OCI的多個版本。主要或次要版本通常每隔幾個月提供一次、服務套件包括新的裝置支援和韌體發行頻率更高。這兩個網站均可從support.netapp.com下載網站取得。某些更新（例如製造商推出的新磁碟機型）會自動推送至OCI軟體。此外、開發修正或更新之後、OCI資料來源裝置集合也可立即在站台上進行修補。



== OCI管理團隊如何優先處理新資料來源的要求？

OCI的產品管理團隊會主動追蹤所有客戶增強功能與互通性功能要求（IFR）。每項申請都會根據客戶需求和整體策略性業務影響、詳細列出、評估可行性並排定優先順序。一旦接受申請、就會根據工作層級來調整申請規模、並排定未來的開發時間。由於開發的開發程序靈活敏捷、因此新的資料來源通常可在定期發行週期之外提供。NetApp客戶代表可協助您進行客戶諮詢、並代表您提交新的申請。無需升級OCI、即可在現場修補資料來源。



== 我的公司完全在Linux上執行。OCI是否能在Linux上運作？

是的、OCI支援多種Linux和Windows功能。請注意、Cognos（OCI搭配Data倉儲使用的IBM報告工具）僅支援Windows、因此如果您使用OCI來報告、就必須在Windows伺服器上執行報告工具。《OCI安裝指南》列出每個OCI元件的伺服器需求和支援的作業系統。



== OCI是否適合沒有網際網路存取的安全環境？

是的、OCI目前已被全球前十大財星雜誌500大企業以及頂尖的銀行、醫療、研究及政府機構所採用。OCI支援美國軍事通用存取卡（CAC）、並針對地理位置分散或防火牆環境提供解決方案。



== 我不斷聽到OnCommand 、《The NetApp Unified Manager》（OCUM）是cDOT的管理解決方案。您可以幫我瞭解為何我也會使用OCI？

NetApp Unified Manager可在儲存陣列的「設備管理」層運作、針對叢集式的叢集式故障（cDOT）陣列及其叢集互連、提供深入的事件和事件型分析Data ONTAP OnCommand 。OCI提供內部部署和全球分散環境的整體檢視、包括7-mode、叢集Data ONTAP 式VMware及其他協力廠商陣列。從VM到磁碟機的端點對端點可見度、可進行容量、效能和成本建模的歷史趨勢預測、以促進資料中心管理的主動式服務品質方法。



== Automation Storefront中提到什麼是「二線ETL」OnCommand Insight ？

部分OnCommand Insight 《自動化Storefront》報告下載中提及的「次要ETL」需求、是指用來叫用擷取資料的額外擷取、轉換及載入（ETL）、以供填入OnCommand Insight 「不實資料」倉儲的已開發專業服務實作。

次要ETL程序的主要用途是預先擷取「批次」資料、以便更複雜的報告能夠更快產生、或排定每日執行。

本次ETL是OnCommand Insight 除了《支援資料倉儲管理指南》中詳述的建議「每日一次」ETL之外的其他功能。

NetApp專業服務部門有資格設定次要ETL指令碼、以避免影響現有OnCommand Insight 的還原報告排程、自動備份、擴充性或其他系統效能活動。如需有關ETL指令碼或資料驗證需求的其他資訊、請聯絡您的NetApp銷售代表、並討論NetApp專業服務如何協助您。
