---
permalink: faq/faq-scale-and-ease-of-use.html 
sidebar: sidebar 
keywords:  
summary: 本常見問題集可解答OnCommand Insight 有關擴充功能及易用性的常見問題。 
---
= 擴充性和易用性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常見問題集可解答OnCommand Insight 有關擴充功能及易用性的常見問題。



== OCI如何擴充？

OCI在互通性及其可取得的資產數量方面處於領導地位、而且佔用空間極少。OCI的核心是需要2部虛擬或實體伺服器：一部用於探索所有資料中心資產的營運伺服器、另一部用於整合式資料倉儲、以供長期歷史報告之用。OCI的企業涵蓋範圍可支援數百個陣列、數萬部虛擬機器、100、000條光纖通道路徑和10、000多個光纖通道連接埠、全都在單一伺服器執行個體中。



== 需要多少人來管理OCI應用程式？

OCI可由單一人員管理。但是OCI的功能可讓業務環境中的多位人員使用、每位人員的角色各不相同、每位人員的報告、疑難排解或分析需求各不相同。我們會盡力將工具維護作業減至最低、從顯示組態問題的健全狀況和通知功能表、到自動探索連接至架構的實體主機。靈活的註釋可為所有類型的使用者、將商業環境帶入生態系統資料。從儲存設備、架構和虛擬化管理員、到容量規劃人員、業務分析師和高階主管、OCI將跨業務封閉環境和技術的資訊共享整合在單一窗口中。



== OCI是否支援自訂報告？

是的。OCI透過IBM Cognos商業智慧工具提供報告功能、讓您從OCI的資料倉儲中收集的資料建立自己的完整自訂報告。



== 建立自訂報告有多簡單？

OCI報告為新手和進階使用者提供功能。OCI提供多種報告撰寫功能、包括「拖放」報告撰寫功能、以及SQL查詢型報告、以供更進階的使用者或專業服務參與。OCI的內建商業智慧解決方案（IBM Cognos）可避免常見的錯誤、例如重複計算容量。隨附隨裝即用報告、小工具、查詢和儀表板等功能、可滿足所有人的報告需求。

客戶也可以從OCI社群商店找到可下載的報告範本。



== OCI是否能以「輕量」的簡易性來展現效能與可用度？

是的。OCI資料倉儲與報告功能可提供色彩增強的報告、例如紅/黃/綠色的「條件式樣式」值。終端使用者和專業服務均可在報告中產生彩色字型或背景。使用OCIs Widget程式庫、可在儀表板中顯示業務特定的效能指標。
