---
permalink: faq/faq-performance-troubleshooting.html 
sidebar: sidebar 
keywords:  
summary: 本常見問題集可解答OnCommand Insight 有關「效能排除」的常見問題。 
---
= 效能疑難排解
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常見問題集可解答OnCommand Insight 有關「效能排除」的常見問題。



== 如何建立環境中所有貪資源的清單？

OCI的關聯分析有助於識別指定服務路徑的貪用和降級資源。關聯功能所產生的分析會在檢視每個物件時即時執行。所提供的分析可大幅縮短疑難排解效能問題和找出根本原因所需的時間。探索所產生的違反已定義效能原則的行為、是探索貪資源或降級資源的一項入門。OCI的異常狀況偵測功能也可做為更主動的方法、在應用程式基礎架構的資源變為服務中斷之前、先識別出其貪婪或降級的資源。使用最新查詢功能的小工具和儀表板都有助於篩選、排序及視覺化資源、其IOPS（貪系）、使用率或延遲均高於預期。



== OCI是否能提供一個診斷效能問題的地方？

是的。在OCI中進行效能疑難排解的方法有多種。OCI有許多可能的警示方法。通常會使用SNMP、Syslog和電子郵件警示。「電子郵件警示」可讓使用者快速點選並啟動OCI中受影響的資源。全域搜尋視窗可讓系統管理員只要輸入資源名稱、就能開始分析情況。

OCI的違規儀表板可讓使用者根據事件數量、持續時間和時間來排定工作優先順序。各種警示類型的範例包括延遲、IOPS、使用率、嚴重性、業務單位、甚至相關的應用程式。

OCI的關聯分析可協助系統管理員比較與受影響資源相關的物件、並判斷其對IOPS、延遲、使用率、CPU和寬帶點數的影響。

OCI在異常狀況偵測與乙太網路監控方面的最新進展、可提供更積極主動的方法、在資源行為變成服務中斷或停機之前偵測異常狀況。

OCI的查詢技術和Widget儀表板可在有組織的檢視中找出具體細節、以鎖定資料中心內的問題領域。



== OCI是否能協助我進行7-mode到cDOT的移轉？

是的、OCI對於現有的工作負載需求和移轉後驗證、提供無價的瞭解。OCI在現代化資料中心方面所扮演的角色、可進行變更管理模擬、移轉前最佳化規劃、以及定義適當的服務層級。只要按幾下滑鼠、OCI就能輕鬆收集並關聯多家廠商環境中數千個NFS共用區和光纖通道路徑的業務影響。從移轉到技術更新、OCI提供可靠、規模適當的移轉途徑、並減輕非計畫性的服務中斷。



== OCI效能監控有多「即時」？

OCI在內部部署和混合雲資料中心管理方面均被視為*近乎即時*。雖然資料來源輪詢可設定為更頻繁地進行、但大多數使用者並不會因為大多數裝置的效能收集時間間隔少於5分鐘而獲得顯著的分析效益。更頻繁的收集可能會對管理中的物件和執行的分析造成不必要的負擔。當然、在某些情況下、可能需要更精細的收集作業、而OCI能提供完整的靈活度、包括可設定的裝置庫存和效能輪詢時間間隔、以符合您的特定資料中心環境需求。



== 為什麼我的「總計」與「讀取」加上「寫入」不同？

在某些情況下、您可能會注意到計數器的_Total與該計數器的_Read__加_writes總和不相等。可能發生這種情況的例子有幾個。

* IOPS *：除了讀取和寫入、儲存陣列或其他資產也會處理與工作負載資料流無關的內部作業。這些作業有時稱為「系統」、「metadata」或「其他」作業、可歸入快照、重複資料刪除或空間重新分配等內部程序。在這些情況下、若要找出特定資產的系統作業量、請從_Total IOPS中減去_read_和_Writ_ IOPS的總和。讀取加上寫入IOPS的總和是與資料流直接相關的總IOPS。

*延遲*：作業的總回應時間（延遲）有時會報告為小於寫入回應時間、因為總回應時間是時間加權平均。I/O工作負載通常會包含比寫入作業更多的讀取作業、而寫入作業通常會觀察到較大的延遲。例如、如果某個工作負載執行10個平均延遲為5毫秒的讀取作業、以及5個平均延遲為10毫秒的寫入作業、則總加權平均延遲時間會以平均讀取延遲的次數來計算、 加上平均寫入延遲的寫入次數、除以I/O作業總數、例如（10 * 5 + 5 * 10）/（10 + 5）= 6.33毫秒。



== OCI和OCUM為何會針對過度組合空間顯示不同的值？

「已配置」空間的《The》（OCUM）OnCommand 概念可能包括FlexVols OnCommand Insight （《內部資料》）可能增加的自動擴充限制。OCI的「容量」並未反映這些自動擴充限制。因此、在有自動擴充FlexVols的環境中、OCUM已配置的容量總計將超過OCI儲存層級的「過度使用容量」總計、而差異則是FlexVols容量與其自動擴充容量之間的差異。
