---
permalink: faq/faq-configuration-and-supported-devices.html 
sidebar: sidebar 
keywords:  
summary: 本常見問題集可解答OnCommand Insight 有關支援的組態和裝置的常見問題。 
---
= 組態和支援的裝置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常見問題集可解答OnCommand Insight 有關支援的組態和裝置的常見問題。



== OCI是否對我的環境進行變更？

不可以OCI是一種唯讀工具、可收集有關您環境的資訊。OCI不會對您的資產或組態進行任何變更。



== OCI需要對我的裝置進行哪些權限層級存取？

在大多數情況下、只讀存取是裝置所需的全部功能。有些解決方案不允許唯讀存取、因此需要適當的提高權限。



== OCI多久收集一次資訊？

OCI通常每5分鐘收集一次效能資料、每隔0.5小時探索一次邏輯和實體架構。OCI會根據建議的最佳實務做法和擴充性來設定預設輪詢時間間隔、但確實允許使用者完全控制這些時間間隔。



== OCI對我的環境有何影響？

OCI的無代理、頻外和被動IP通訊、有助於將資料中心生態系統的設定、維護和影響降至最低。OCI的績效開發團隊採取重大措施、將監控效能本身活動對資料中心效能的任何影響降至最低。在正常的作業環境中、影響可視為微不足道、而且在高使用率或效能不佳的技術平台中、也可予以緩和或加強。如OnCommand Insight 需詳細資訊、請參閱《The《The《The》《The《The《



== 如何列出OCI中的所有主機/虛擬機器？

OCI對小工具和查詢清單可能性的讚美、可用來提供資料中心資產的庫存樣式清單。可將虛擬機器清單放入磁碟中、並在其中建立許多架構、以便查詢、小工具、儀表板和資料倉儲報告、並可透過RESTful API存取。



== OCI是否為相關的非Hypervisor主機（例如實體伺服器）提供相同類型的支援？

VMware等Hypervisor提供ESXi主機及其相關虛擬機器（VM）的詳細資訊。對於實體伺服器、OCI會收集最多至主機HBA的度量資料。OCI採用獨特的方法、利用專利申請中的技術來探索實體伺服器。一旦發現儲存設備和（或）交換器、實體伺服器的主機名稱就會包含在Fabric別名資訊中。OCI會選取這些主機名稱、並在DNS中加以比對、然後自動將主機帶入OCI。這項技術可大幅減少手動輸入更新和工具庫存維護的需求。



== OCI是否在異質環境中提供相同的裝置度量深度（同位元檢查）？

第三方平台和廠商技術之間的標準化、通用性和命名方式各有不同。OCI嘗試將容量與效能資訊標準化為一致的架構。部分容量和效能指標是從裝置的計數器原生提供、例如IOPs、延遲和原始容量。若未提供計數器、OCI可嘗試彙總值（例如、將IOPs或基礎磁碟區容量總計）、若兩者皆不可用、OCI將嘗試透過各種運算演算法來衍生度量值。OCI提供一般的SNMP整合功能、可整合目前未由OCI收集的其他度量。



== OCI是否支援光纖通道交換器？

是的、除了從您的儲存資產收集資料之外、OCI也會從您環境中的Cisco、Brocade和QLogic交換器取得庫存和效能資料。



== 整個基礎架構的拓撲檢視是否可用？OCI是否顯示「端點對端點可見度」？

是的、OCI會動態探索及對應邏輯和實體架構、提供運算、架構、虛擬化程式和後端儲存設備的互動式端點對端點拓撲檢視。拓撲圖示可快速導覽受影響的資源、並協助識別共享儲存環境中的工作負載和違規情形。
