---
permalink: faq/faq-insight-licensing.html 
sidebar: sidebar 
keywords:  
summary: 關於OnCommand Insight 資訊共享的常見問題解答。 
---
= 資訊授權OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
關於OnCommand Insight 資訊共享的常見問題解答。



== OCI授權總覽

OCI係依容量授權。客戶必須為想要啟用的每個模組購買授權：

*「激發需求」*是保證、執行及規劃的先決條件、並非自行提供。「探索」是以TB的託管容量授權。

* Assur*是以TB的託管容量授權（所有儲存基礎架構的單一單位收費：FC、NAS、iSCSI、FCoE）。

*執行*是以TB的託管容量授權。

* Plan *是以TB託管容量授權。

「老舊容量」是指在格式化之前、實體磁碟、虛擬磁碟和磁帶的原始容量。這適用於Insight在內部部署和雲端中探索到的所有儲存設備。

大部分的資料來源都在考慮磁碟原始基礎2容量。磁碟角色無需考量、例如備用磁碟、未指派的磁碟或RAID磁碟。

Insight授權有兩種類型：* Perpetual *和* Subscription*。

*永久授權*可讓您根據適用的授權條款、無限期使用取得的特定軟體版本/版本。如果您已購買軟體支援方案（SSP）、NetApp可在NetApp 支援網站 更新依照其支援服務條款提供時、透過The Update取得市售軟體更新。NetApp也提供存取NetApp技術支援中心所決定的特殊修補程式。

*訂購*是軟體的固定期限授權、賦予下列權利：

* 僅限在有限期間（最常見的12個月）內於內部部署使用軟體、並遵守適用的授權條款
* 在期限內接收軟體支援（先前稱為SSP）
* 雖然實際上、被授權人可能會使用最新的市售版本、版本或更新、但若有任何可用的版本、也會獲得軟體支援


在每個固定期限（最常見的是12個月）結束時、授權可續約一段固定期限（最常見的是12個月）。如果授權未續約、被授權人將不再擁有使用軟體的權利、將不再享有SSP的權益、且被授權人必須銷毀軟體的所有複本。



== 深入瞭解OCI授權模組

OCI擁有4個核心授權模組、可滿足現今的資料中心環境需求。這些模組包括*探索、執行、保證及規劃*。探索是基礎模組、所有其他模組購買都需要探索。

利用* Discover（探索）*模組、OCI可以在資料中心找到資產、並動態對應裝置服務路徑。提供容量、廠商資訊、機型、韌體和序號等資訊。

*執行*是OCI的效能收集模組。執行會擷取IOPS、處理量、延遲、CPU和記憶體資訊、並提供其他分析功能。

* Assur*的目標是光纖通道環境和效率技術。它有助於識別及管理光纖通道和iSCSI環境中的風險。Assure也能協助您識別、對應及警示遮罩、對應及分區服務路徑項目、以及效率最佳實務原則、例如網路備援、交換器躍點、連出比率和精簡配置。

*規劃*可在混合式內部部署與全球分散的資料中心環境中、辨識並預測運算、網路及各種儲存類型（cDOT、7-mode、協力廠商）的趨勢。可延長保留時間。資料倉儲內建智慧功能、可讓您撰寫報告、避免在企業共享儲存環境中重複計算度量。它能夠產生並排程「隨裝即用」的產品化報告、或是使用其「拖放」整合式報告撰寫工具來建立自己的報告。
