---
permalink: config-admin/about-oncommand-insight-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: 包含機器學習異常偵測分析功能、可清楚掌握應用程式的基礎架構、並在效能異常狀況變成服務中斷之前予以識別OnCommand Insight 。 
---
= 功能異常偵測的運作方式OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
包含機器學習異常偵測分析功能、可清楚掌握應用程式的基礎架構、並在效能異常狀況變成服務中斷之前予以識別OnCommand Insight 。

異常分析可協助您識別應用程式的正常作業工作負載範圍、並在效能變更超出預期層級時通知您。應用程式異常狀況偵測引擎會擷取Insight收集的效能指標、並識別應用程式基礎架構中的異常狀況。

您可以使用異常偵測來執行下列工作：

* 識別應用程式基礎架構行為的重大變更
* 追蹤整個堆疊和多個計數器的應用程式
* 診斷應用程式工作負載中定期發生事件的原因
* 與使用靜態臨界值的效能計數器資料相比、提供更完整的資訊集
* 以改良的被動模式監控、透過端點對端點的拓撲檢視、以及專注於最異常行為的能力。


異常狀況偵測引擎使用Insight資料進行應用程式分析。首次啟動監控時、分析引擎最多可擷取14天的歷史效能資料。收集資料的時間長達數週甚至數月、可提供更準確的特定資源資料。這些資料包括下列計數器的總計：

|===


| 物件 | 計數器 


 a| 
VM
 a| 
延遲、IOPS



 a| 
Hypervisor
 a| 
CPU使用率、IOPS



 a| 
邊際連接埠
 a| 
零的寬帶點數



 a| 
儲存節點
 a| 
延遲、使用率、IOPS



 a| 
Volume
 a| 
延遲、IOPS



 a| 
內部Volume
 a| 
延遲、IOPS



 a| 
儲存資源池
 a| 
IOPS、使用率

|===
在Insight伺服器上啟用效能資料歸檔時、會歸檔由異常偵測引擎收集的資料。請參閱「系統健全狀況」頁面、以判斷是否已啟用歸檔。

異常偵測引擎是在獨立於Insight伺服器的伺服器上執行。可在實體機器或VM上設定。如OnCommand Insight 需詳細資訊、請參閱《適用於Windows或Linux的《支援》。
