---
permalink: config-admin/advanced-asset-search-techniques-new.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用多種搜尋技術來搜尋監控環境中的資料或物件。 
---
= 進階搜尋技術
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用多種搜尋技術來搜尋監控環境中的資料或物件。



== 萬用字元搜尋

您可以使用*字元執行多個字元的萬用字元搜尋。例如、_applic* n_會傳回應用程式。



== 用於搜尋的詞彙

片語是一組字詞、以雙引號括住、例如「paw VNX LUN 5」。您可以使用雙引號來搜尋名稱或屬性中含有空格的文件。



== 布林運算子

使用布林運算子、您可以合併多個字詞、形成更複雜的查詢。

* *或*
+
** OR運算子是預設的聯合運算子。
+
如果兩個詞彙之間沒有布林運算子、則會使用OR運算子。

** OR運算子會連結兩個詞彙、如果文件中有任一詞彙、就會找到相符的文件。
+
例如、「'sorage or NetApp'」會搜尋含有「'sorage'」或「'NetApp'」的文件。

** 對於符合大部分條款的文件、會給予高分。


* *和*
+
您可以使用AND運算子來尋找單一文件中同時存在兩個搜尋字詞的文件。例如、「'aurora and NetApp'」會搜尋同時包含「shorage'」和「'NetApp'」的文件。

+
您可以使用符號&&取代詞AND。

* *不*
+
當您使用Not運算子時、搜尋結果中會排除所有包含「Not」字詞之後的文件。例如、「'sorage not NetApp'」會搜尋僅包含「shorage」而非「'NetApp'」的文件。

+
您可以使用符號！而不是「不」這個字。





== 字首和字尾搜尋

* 一旦您開始輸入搜尋字串、搜尋引擎就會執行前置詞和後置字元搜尋、以找出最相符的字元。
* 完全符合的分數比前置詞或後置字元相符的分數高。分數是根據搜尋詞彙與實際搜尋結果之間的距離來計算。例如、我們有三個儲存室：「'aurora'」、「'aurora1'」和「'aurora11'」。搜尋「aur」將會傳回所有三個儲存室。不過、「'aurora'」的搜尋結果會獲得最高分數、因為它距離前置字元搜尋字串最近。
* 搜尋引擎也會以相反順序搜尋詞彙、讓您執行後置搜尋。例如、當您在搜尋方塊中輸入「'345」時、搜尋引擎會搜尋「'345」。
* 搜尋不區分大小寫。




== 使用索引詞彙進行搜尋

符合更多索引詞彙的搜尋結果會獲得較高的分數。

搜尋字串會依空格分割成不同的搜尋字詞。例如、搜尋字串「'sorage aurora NetApp'」分為三個關鍵字：「'torage'」、「'aurora'」和「'NetApp'」。搜尋是使用這三個詞彙來執行。大部分符合這些詞彙的文件將獲得最高分數。您提供的資訊越多、搜尋結果就越好。例如、您可以依儲存設備的名稱和模式來搜尋儲存設備。

UI會顯示各類別的搜尋結果、每個類別的結果最多三項。如果您找不到所需的文件、可以在搜尋字串中加入更多字詞、以改善搜尋結果。

下表提供可新增至搜尋字串的索引詞彙清單。

|===


| 類別 | 索引詞彙 


 a| 
儲存設備
 a| 
* 「太老了」
* 名稱
* 廠商
* 模型




 a| 
StoragePool
 a| 
* 「toragepool」
* 名稱
* 儲存設備名稱
* 儲存設備的IP位址
* 儲存設備的序號
* 儲存設備廠商
* 儲存模式
* 所有相關內部磁碟區的名稱
* 所有相關磁碟的名稱




 a| 
內部Volume
 a| 
* 「內部容量」
* 名稱
* 儲存設備名稱
* 儲存設備的IP位址
* 儲存設備的序號
* 儲存設備廠商
* 儲存模式
* 儲存資源池名稱
* 所有相關共用的名稱
* 所有相關應用程式和商業實體的名稱




 a| 
Volume
 a| 
* 「Volume」
* 名稱
* 標籤
* 所有內部磁碟區的名稱
* 儲存資源池名稱
* 儲存設備名稱
* 儲存設備的IP位址
* 儲存設備的序號
* 儲存設備廠商
* 儲存模式




 a| 
儲存節點
 a| 
* 「太過程式碼」
* 名稱
* 儲存設備名稱
* 儲存設備的IP位址
* 儲存設備序號
* 儲存設備廠商
* 儲存模式




 a| 
主機
 a| 
* 「主機」
* 名稱
* IP位址
* 所有相關應用程式和商業實體的名稱




 a| 
資料存放區
 a| 
* 「Datastore」
* 名稱
* 虛擬中心IP
* 所有Volume的名稱
* 所有內部磁碟區的名稱




 a| 
虛擬機器
 a| 
* 「虛擬機器」
* 名稱
* DNS名稱
* IP位址
* 主機名稱
* 主機的IP位址
* 所有資料存放區的名稱
* 所有相關應用程式和商業實體的名稱




 a| 
交換器（一般和NPV）
 a| 
* 「女魔女」
* IP 位址
* WWN
* 名稱
* 序號
* 模型
* 網域ID
* 網路名稱
* 網路的WWN




 a| 
應用程式
 a| 
* 「應用程式」
* 名稱
* 租戶
* 業務線
* 業務單位
* 專案




 a| 
磁帶
 a| 
* 「'tape」
* IP 位址
* 名稱
* 序號
* 廠商




 a| 
連接埠
 a| 
* 「'port'」
* WWN
* 名稱




 a| 
網路
 a| 
* 「Fabric」
* WWN
* 名稱


|===