---
permalink: config-admin/brocade-fc-switch-firmware-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 使用Brocade FC交換器（SSH）資料來源、探索執行因素作業系統（FOS）韌體4.2及更新版本之Brocade或重新品牌交換器裝置的庫存OnCommand Insight 。同時支援FC交換器和存取閘道模式的裝置。 
---
= Brocade FC交換器資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援使用Brocade FC交換器（SSH）資料來源來探索執行因素作業系統（FOS）韌體4.2及更新版本之Brocade或重新品牌交換器裝置的庫存OnCommand Insight 。同時支援FC交換器和存取閘道模式的裝置。



== 術語

從Brocade FC交換器資料來源取得下列庫存資訊OnCommand Insight 。對於Insight取得的每種資產類型、都會顯示此資產最常用的術語。檢視或疑難排解此資料來源時、請謹記下列術語：

|===


| 廠商/模型術語 | Insight術語 


 a| 
交換器
 a| 
交換器



 a| 
連接埠
 a| 
連接埠



 a| 
虛擬架構、實體架構
 a| 
網路



 a| 
區域
 a| 
區域



 a| 
邏輯交換器
 a| 
邏輯交換器



 a| 
LSAN區域
 a| 
IVR區域

|===
[NOTE]
====
這些只是通用的術語對應、可能不代表此資料來源的每個案例。

====


== 需求

* 擷取單元（本機或遠端）會啟動與Brocade交換器TCP連接埠22的連線、以收集庫存資料。AU也會啟動連接至udp連接埠161的連線、以收集效能資料。
* 網路中的所有交換器都必須具備IP連線能力。如果您選取「Discover all switches in the fabric」（探索網路中的所有交換器）核取方塊、OCI會識別網路中的所有交換器；不過、它需要IP連線到這些額外交換器才能探索這些交換器。
* 網路中的所有交換器都需要相同的帳戶。您可以使用Putty（開放原始碼終端機模擬器）來確認存取。
* 如果安裝了Perform授權、則光纖網路中的所有交換器都必須開啟連接埠161和162、才能進行SNMP效能輪詢。
* SNMP唯讀社群字串




== 組態

|===


| 欄位 | 說明 


 a| 
交換器IP
 a| 
交換器的IP位址或完整網域名稱



 a| 
使用者名稱
 a| 
交換器的使用者名稱



 a| 
密碼
 a| 
用於交換器的密碼



 a| 
SNMP版本
 a| 
SNMP版本



 a| 
SNMP社群字串
 a| 
用於存取交換器的SNMP唯讀社群字串



 a| 
SNMP使用者名稱
 a| 
SNMP版本傳輸協定使用者名稱（僅適用於SNMP v3）



 a| 
SNMP密碼
 a| 
SNMP版本傳輸協定密碼（僅適用於SNMP v3）

|===


== 進階組態

|===


| 欄位 | 說明 


 a| 
網路名稱
 a| 
要由資料來源回報的網路名稱。保留空白以將網路名稱報告為WWN。



 a| 
排除裝置
 a| 
要從輪詢中排除的裝置ID清單、以逗號分隔



 a| 
庫存輪詢時間間隔（分鐘）
 a| 
庫存輪詢之間的時間間隔（預設為15分鐘）



 a| 
逾時（秒）
 a| 
連線逾時（預設30秒）



 a| 
橫幅等待逾時（秒）
 a| 
SSH橫幅等待逾時（預設5秒）



 a| 
管理網域作用中
 a| 
如果使用管理網域、請選取



 a| 
擷取MPR-資料
 a| 
選取以從多重傳輸協定路由器（MPR-）取得路由資料



 a| 
啟用資料綁定
 a| 
選取以在從裝置接收SNMP設陷時啟用擷取。如果您選取「啟用補漏白」、也必須啟動SNMP。



 a| 
設陷之間的最短時間（秒）
 a| 
擷取嘗試之間由陷阱觸發的最短時間（預設為10秒）



 a| 
探索網路中的所有交換器
 a| 
選取以探索網路中的所有交換器



 a| 
選擇「偏好HBA、而不是」區域別名
 a| 
選擇是否偏好HBA或區域別名



 a| 
效能意見調查時間間隔（秒）
 a| 
效能輪詢之間的時間間隔（預設為300秒）



 a| 
SNMP驗證傳輸協定
 a| 
SNMP驗證傳輸協定（僅限SNMP v3）



 a| 
SNMP隱私權傳輸協定
 a| 
SNMP隱私傳輸協定（僅限SNMP v3）



 a| 
SNMP隱私密碼
 a| 
SNMP隱私密碼（僅限SNMP v3）



 a| 
SNMP重試次數
 a| 
SNMP重試嘗試次數



 a| 
SNMP逾時（毫秒）
 a| 
SNMP逾時（預設值5000毫秒）

|===