---
permalink: config-admin/brocade-sphereon-intrepid-switch-snmp-data-source.html 
sidebar: sidebar 
keywords:  
summary: 使用Brocade Sphereon / Intrepid交換器（SNMP）資料來源、探索Brocade Sphereon或Intrepid交換器的庫存OnCommand Insight 。 
---
= Brocade Sphereon / Intrepid交換器資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用Brocade Sphereon / Intrepid交換器（SNMP）資料來源、探索Brocade Sphereon或Intrepid交換器的庫存OnCommand Insight 。



== 需求

[NOTE]
====
此資料收集器無法從OnCommand Insight 功能介紹7.3.11開始使用。

====
* 網路中的所有交換器都必須具備IP連線能力。如果您選取「Discover all switches in the fabric」（探索網路中的所有交換器）核取方塊、OCI會識別網路中的所有交換器；不過、它需要IP連線到這些額外交換器才能探索這些交換器。
* 如果使用SNMP V1或SNMP V2、則為唯讀社群字串。
* 以HTTP存取交換器以取得分區資訊。
* 執行來存取驗證 `snmpwalk` 公用程式至交換器（請參閱 `<install_path\>\bin\)`。




== 組態

|===


| *欄位* | *說明* 


 a| 
Sphereon交換器
 a| 
交換器的IP位址或完整網域名稱



 a| 
SNMP版本
 a| 
SNMP版本



 a| 
SNMP社群
 a| 
用於存取交換器的SNMP唯讀社群字串



 a| 
使用者名稱
 a| 
交換器的SMI-S使用者名稱（僅限SNMP v3）



 a| 
密碼
 a| 
交換器的SMI-S密碼（僅限SNMP v3）

|===


== 進階組態

|===


| *欄位* | *說明* 


 a| 
庫存輪詢時間間隔（分鐘）
 a| 
庫存輪詢之間的時間間隔（預設為15分鐘）



 a| 
SNMP驗證傳輸協定
 a| 
SNMP驗證傳輸協定（僅限v3）



 a| 
SNMP隱私權傳輸協定
 a| 
SNMP隱私傳輸協定（僅限v3）



 a| 
SNMP隱私密碼
 a| 
SNMP隱私密碼



 a| 
SNMP重試次數
 a| 
SNMP重試嘗試次數



 a| 
SNMP逾時（毫秒）
 a| 
SNMP逾時（預設值5000毫秒）



 a| 
網路名稱
 a| 
要由資料來源回報的網路名稱。保留空白以將網路名稱報告為WWN。



 a| 
啟用資料綁定
 a| 
選取以在從裝置接收SNMP設陷時啟用擷取。如果您選取「啟用補漏白」、也必須啟動SNMP。



 a| 
Ttraps之間的最短時間（秒）
 a| 
擷取嘗試之間由陷阱觸發的最短時間（預設為10秒）



 a| 
效能意見調查時間間隔（秒）
 a| 
效能輪詢之間的時間間隔（預設為300秒）

|===