---
permalink: config-admin/cdot-landing-page-terminology-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: 適用於NetApp叢集Data ONTAP 式物件或參考資料的術語、可在NetApp叢集式物件資源庫資產登陸頁面找到。 
---
= 叢集Data ONTAP 式功能儲存資源池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於NetApp叢集Data ONTAP 式物件或參考資料的術語、可在NetApp叢集式物件資源庫資產登陸頁面找到。



== 叢集Data ONTAP 式的《邊區儲存資源池術語》

下列詞彙適用於您在NetApp叢集式Data ONTAPStorage Pool資產登陸頁面上可能找到的物件或參考資料。其中許多術語也適用於其他資料收集器。

* 儲存設備：此儲存設備所使用的儲存陣列。必填。
* 鍵入：列舉的可能性清單中的描述性值。最常見的是「Aggregate」或「RAID Group」。
* 節點-如果此儲存陣列的架構使資源池屬於特定儲存節點、則此處的名稱將會顯示為其專屬登陸頁面的超連結。
* 使用Flash Pool（是/無值）、這種SATA/SAS型集區是否使用SSD來快取加速？
* 備援：RAID層級或保護方案。RAID-DP為雙同位元檢查、RAID_tp為三同位元檢查。
* 容量：此處的值是已用邏輯容量、可用容量和邏輯總容量、以及這些容量使用的百分比。
* 過度委派容量：如果使用效率技術、您已將容量總計或內部Volume容量分配給大於儲存資源池邏輯容量的總和、則此處的百分比值將大於0%。
* Snapshot（快照）-使用的快照容量和總容量（如果您的儲存資源池架構將部分容量專用於專為快照而設計的區段區域）。在不支援支援的情況下、支援的部分可能會出現這個問題、而其他的不支援的組態則較少ONTAP MetroCluster ONTAP 。
* 使用率-百分比值、顯示此儲存資源池中任何磁碟貢獻容量的最高磁碟使用率百分比。磁碟使用率不一定與陣列效能有密切的關聯、因為磁碟重建、重複資料刪除活動等原因、在缺乏主機驅動的工作負載的情況下、使用率可能會很高。此外、許多陣列的複寫實作可能會提高磁碟使用率、而不會顯示為內部磁碟區或磁碟區工作負載。
* IOPS：所有磁碟的IOPs總和、可為此儲存資源池提供容量。
* 處理量：所有磁碟的總處理量、可為此儲存資源池提供容量。

