---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: 安全性原則可能需要您在OnCommand Insight 您的環境中變更密碼。某部伺服器上的某些密碼存在於環境中的不同伺服器上、需要您變更兩部伺服器上的密碼。例如、當您變更Insight Server上的「詳細目錄」使用者密碼時、您必須符合Data倉儲伺服器連接器上針對該Insight Server所設定的「詳細目錄」使用者密碼。 
---
= 變更OnCommand Insight 內部使用者密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安全性原則可能需要您在OnCommand Insight 您的環境中變更密碼。某部伺服器上的某些密碼存在於環境中的不同伺服器上、需要您變更兩部伺服器上的密碼。例如、當您變更Insight Server上的「Inventory」使用者密碼時、您必須符合Data倉儲伺服器Connector上針對該Insight Server所設定的「Inventory」使用者密碼。



== 開始之前

[NOTE]
====
變更密碼之前、您應該先瞭解使用者帳戶的相依性。若未更新所有必要伺服器上的密碼、Insight元件之間的通訊將會失敗。

====


== 關於這項工作

下表列出Insight Server的內部使用者密碼、並列出具有相依密碼的Insight元件、這些元件必須符合新密碼。

|===


| Insight Server密碼 | 必要變更 


 a| 
內部_
 a| 



 a| 
併購
 a| 
劉羅



 a| 
dwh_internal
 a| 
資料倉儲



 a| 
主機
 a| 



 a| 
庫存
 a| 
資料倉儲



 a| 
根
 a| 

|===
下表列出Data倉儲的內部使用者密碼、並列出Insight元件、這些元件的相依密碼必須與新密碼相符。

|===


| 資料倉儲密碼 | 必要變更 


 a| 
Cogns_admin
 a| 



 a| 
dwh
 a| 



 a| 
Dwh_internal（使用伺服器連接器組態UI變更）
 a| 
Insight伺服器



 a| 
dwhuser
 a| 



 a| 
主機
 a| 



 a| 
庫存（使用伺服器連接器組態UI變更）
 a| 
Insight伺服器



 a| 
根
 a| 

|===
*變更DWH伺服器連線組態Ui*中的密碼

下表列出了劉的使用者密碼、並列出了Insight元件、這些元件的相依密碼必須與新密碼相符。

|===


| 劉密碼 | 必要變更 


 a| 
併購
 a| 
Insight Server、Rau

|===