---
permalink: config-admin/cisco-fc-switch-firmware-snmp-data-source.html 
sidebar: sidebar 
keywords:  
summary: 使用Cisco FC交換器韌體2.0+（SNMP）資料來源、探索Cisco MDS Fibre Channel交換器的庫存、以及啟用FC服務的各種Cisco Nexus FCoE交換器OnCommand Insight 。此外、您也可以利用此資料來源、探索以NPV模式執行的許多Cisco裝置機型。 
---
= Cisco FC交換器韌體（SNMP）資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用Cisco FC交換器韌體2.0+（SNMP）資料來源、探索Cisco MDS Fibre Channel交換器的庫存、以及啟用FC服務的各種Cisco Nexus FCoE交換器OnCommand Insight 。此外、您也可以利用此資料來源、探索以NPV模式執行的許多Cisco裝置機型。



== 術語

從Cisco FC交換器資料來源取得下列庫存資訊OnCommand Insight 。對於Insight取得的每種資產類型、都會顯示此資產最常用的術語。檢視或疑難排解此資料來源時、請謹記下列術語：

|===


| 廠商/模型術語 | Insight術語 


 a| 
交換器
 a| 
交換器



 a| 
連接埠
 a| 
連接埠



 a| 
vSAN
 a| 
網路



 a| 
區域
 a| 
區域



 a| 
邏輯交換器
 a| 
邏輯交換器



 a| 
名稱伺服器項目
 a| 
名稱伺服器項目



 a| 
VSAN間路由（IVR）區域
 a| 
IVR區域

|===
[NOTE]
====
這些只是通用的術語對應、可能不代表此資料來源的每個案例。

====


== 需求

* 網路或個別交換器中的一個交換器IP位址
* 機箱探索、以啟用網路探索
* 如果使用SNMP V2、則為唯讀社群字串
* 連接埠161用於存取裝置
* 使用存取驗證 `snmpwalk` 公用程式至交換器（請參閱 `<install_path\>\bin\`）




== 組態

|===


| 欄位 | 說明 


 a| 
Cisco交換器IP
 a| 
交換器的IP位址或完整網域名稱



 a| 
SNMP版本
 a| 
擷取效能時需要SNMP v2或更新版本



 a| 
SNMP社群字串
 a| 
用於存取交換器的SNMP唯讀社群字串（不適用於SNMP v3）



 a| 
使用者名稱
 a| 
交換器的使用者名稱（僅限SNMP v3）



 a| 
密碼
 a| 
用於交換器的密碼（僅限v3）

|===


== 進階組態

|===


| 欄位 | 說明 


 a| 
庫存輪詢時間間隔（分鐘）
 a| 
庫存輪詢之間的時間間隔（預設為40分鐘）



 a| 
SNMP驗證傳輸協定
 a| 
SNMP驗證傳輸協定（僅限v3）



 a| 
SNMP隱私權傳輸協定
 a| 
SNMP隱私傳輸協定（僅限v3）



 a| 
SNMP隱私密碼
 a| 
SNMP隱私密碼



 a| 
SNMP重試次數
 a| 
SNMP重試嘗試次數



 a| 
SNMP逾時（毫秒）
 a| 
SNMP逾時（預設值5000毫秒）



 a| 
啟用資料綁定
 a| 
選取以啟用補漏白。如果啟用補漏白、您也必須啟動SNMP通知。



 a| 
設陷之間的最短時間（秒）
 a| 
擷取嘗試之間由陷阱觸發的最短時間（預設為10秒）



 a| 
探索All Fabric交換器
 a| 
選取以探索網路中的所有交換器



 a| 
排除裝置
 a| 
要從輪詢中排除的裝置IP清單、以逗號分隔



 a| 
包括裝置
 a| 
輪詢中要包含的裝置IP清單、以逗號分隔



 a| 
檢查裝置類型
 a| 
選取此選項、只接受明確宣稱自己為Cisco裝置的裝置



 a| 
主要別名類型
 a| 
提供別名解析的第一個偏好設定。請從下列選項中選擇：

* *設備別名*
+
這是連接埠WWN（pWWN）的易用名稱、可視需要用於所有組態命令。Cisco MDS 9000系列中的所有交換器都支援分散式裝置別名服務（裝置別名）。

* *無*
+
請勿回報任何別名

* *連接埠說明*
+
可協助識別連接埠清單中的連接埠的說明

* *區域別名（全部）*
+
連接埠的使用者易記名稱、僅可用於分區組態

* *區域別名（僅作用中）*
+
連接埠的使用者易記名稱、只能用於作用中組態。這是預設值。





 a| 
次要別名類型
 a| 
提供別名解析的第二個偏好設定



 a| 
第三別名類型
 a| 
提供別名解析的第三個偏好設定



 a| 
啟用SANTAP Proxy模式支援
 a| 
如果您的Cisco交換器在Proxy模式下使用SANTAP、請選取此選項。如果您使用的是EMC RecoverPoint、則可能是使用SANTap。



 a| 
效能意見調查時間間隔（秒）
 a| 
效能輪詢之間的時間間隔（預設為300秒）

|===