---
permalink: config-admin/device-resolution.html 
sidebar: sidebar 
keywords:  
summary: 您需要探索OnCommand Insight 所有想要用NetApp監控的裝置。為了準確追蹤環境中的效能與庫存、探索是必要的。一般而言、環境中大部分的裝置都是透過自動裝置解析功能來探索。 
---
= 裝置解析度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要探索OnCommand Insight 所有想要用NetApp監控的裝置。為了準確追蹤環境中的效能與庫存、探索是必要的。一般而言、環境中大部分的裝置都是透過自動裝置解析功能來探索。

[NOTE]
====
如果您正在執行升級、且升級時所在的系統中有非作用中的自動解決規則、則這些規則將會在升級期間刪除。若要保留非作用中的自動解決規則、請在執行升級之前先啟動規則（勾選方塊）。

====
在您安裝及設定資料來源之後、系統會識別環境中的裝置、包括交換器、儲存陣列、以及Hypervisor和VM的虛擬基礎架構。不過、這通常無法識別環境中100%的裝置。

在設定資料來源類型裝置之後、最佳做法是運用裝置解決規則來協助識別環境中剩餘的未知裝置。裝置解析度可協助您解決下列裝置類型的未知裝置：

* 實體主機
* 儲存陣列
* 磁帶
* 交換器


在裝置解析度之後、仍為「未知」的裝置會被視為一般裝置、您也可以在查詢和儀表板上顯示這些裝置。

接著建立的規則會在新增至環境時、自動識別具有類似屬性的新裝置。在某些情況下、裝置解析功能也允許手動識別、繞過Insight中未發現裝置的裝置解析規則。

不完整的裝置識別可能導致下列問題：

* 路徑不完整
* 未識別的多重路徑連線
* 無法將應用程式分組
* 拓撲視圖不準確
* 資料倉儲和報告中的資料不準確


「裝置解析度」功能（*管理*>*裝置解析度*）包含下列索引標籤、每個索引標籤在裝置解析度規劃和檢視結果中扮演著重要角色：

* 「FC identify」（FC識別）包含未透過自動裝置解析解決的光纖通道裝置WWN清單和連接埠資訊。此索引標籤也會識別已識別的裝置百分比。
* 「IP identify」（IP識別）包含存取CIFS共用和NFS共用的裝置清單、這些裝置無法透過自動裝置解析來識別。此索引標籤也會識別已識別的裝置百分比。
* 「自動解析規則」包含執行光纖通道裝置解析時所執行的規則清單。您可以建立這些規則來解析未識別的光纖通道裝置。
* 「偏好設定」提供組態選項、可讓您針對環境自訂裝置解析度。

