---
permalink: config-admin/hds-landing-page-terminology-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: 適用於HDS儲存資源池資產登陸頁面上可能找到的物件或參考的詞彙。 
---
= HDS儲存資源池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於HDS儲存資源池資產登陸頁面上可能找到的物件或參考的詞彙。



== HDS儲存資源池術語

下列詞彙適用於HDS儲存資源池資產登陸頁面上可能找到的物件或參考資料。其中許多術語也適用於其他資料收集器。

* 類型：此處的值為：
+
** 保留-如果此資源池專用於資料磁碟區以外的用途、例如、日誌記錄、快照
** 精簡配置（如果這是HDP池）
** RAID Group（RAID群組）-您可能不會因為下列幾個原因而看到這些資訊：
+
保監處採取堅定的立場、避免在任何成本下重複計算容量。在HDS上、通常需要從磁碟建立RAID群組、在這些RAID群組上建立集區磁碟區、以及從這些集區磁碟區建構集區（通常是HDP、但可能是特殊用途）。如果OCI同時報告基礎RAID群組和集區、則其原始容量總和將會大幅超過磁碟總和。

+
相反地、OCI的HDS HDS-Data Collector會根據集區磁碟區的容量、任意縮減RAID群組的大小。這可能導致OCI完全不報告RAID群組。此外、任何產生的RAID群組都會以旗標方式標示、使其在OCI WebUI中不可見、但它們確實會流入OCI資料倉儲（DWH）。這些決策的目的是為了避免大部分使用者不關心的問題、因為如果HDS陣列有可用容量為50MB的RAID群組、您可能無法使用該可用空間來獲得任何有意義的結果。



* 節點-不適用、因為HDS集區不會繫結至任何一個特定節點
* 備援：集區的RAID層級。可能是由多種RAID類型所組成的HDP集區有多個值
* 容量%：集區用於資料使用量的百分比、以及已使用的GB和集區的總邏輯GB大小
* 過度委派容量：一種衍生值、表示「此資源池的邏輯容量因邏輯磁碟區總和超過此百分比之資源池邏輯容量而超額訂閱」
* Snapshot：顯示此資源池中保留用於快照使用的容量

