---
permalink: config-admin/ibm-svc-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM SVC資料來源會使用SSH收集庫存與效能資料、以支援執行SVC作業系統的各種裝置。支援的裝置清單包括SVC、v7000、v5000和v3700等機型。如需支援的機型和韌體版本、請參閱Insight資料來源支援對照表。 
---
= IBM SVC資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM SVC資料來源會使用SSH收集庫存與效能資料、以支援執行SVC作業系統的各種裝置。支援的裝置清單包括SVC、v7000、v5000和v3700等機型。如需支援的機型和韌體版本、請參閱Insight資料來源支援對照表。



== 術語

從IBM SVC資料來源取得下列庫存資訊OnCommand Insight 。對於Insight取得的每種資產類型、都會顯示此資產最常用的術語。檢視或疑難排解此資料來源時、請謹記下列術語：

|===


| 廠商/模型術語 | Insight術語 


 a| 
磁碟機
 a| 
磁碟



 a| 
叢集
 a| 
儲存設備



 a| 
節點
 a| 
儲存節點



 a| 
Mdisk群組
 a| 
儲存資源池



 a| 
vDisk
 a| 
Volume



 a| 
磁碟
 a| 
後端LUN

|===
[NOTE]
====
這些只是通用的術語對應、可能不代表此資料來源的每個案例。

====


== 庫存需求

* 每個SVC叢集的IP位址
* 連接埠22可用
* 您可以透過Insight產生的公開和私密金鑰組、或是重複使用已在SVC上使用的金鑰組
+
如果您要重複使用現有的金鑰組、則必須將其從Putty格式轉換為OpenSSH格式。

* 安裝在SVC叢集上的公開金鑰
* 需要在資料來源中識別私密金鑰
* 存取驗證：開啟 `ssh` 使用私密金鑰與SVC叢集之間的工作階段


[NOTE]
====
無需安裝協力廠商軟體。

====


== 效能要求

* SVC主控台、適用於任何SVC叢集、且適用於SVC探索基礎套件。
* 只有將效能資料檔案從叢集節點複製到組態節點時、才需要管理存取層級。
+
[NOTE]
====
由於SVC基礎探索套件不需要此存取層級、因此SVC基礎使用者可能無法成功運作。

====
* 需要連接埠22
* 必須為此使用者產生私有和公有SSH金鑰、並儲存私密金鑰、以便從擷取單位存取。如果SVC基礎使用者擁有適當的權限、則相同的使用者和金鑰也能正常運作。相同的SSH金鑰可用於庫存和效能資料。
* 透過SSH連線至SVC叢集並執行下列作業、以啟用資料收集： `svctask startstats -interval 1`
+
[NOTE]
====
或者、也可以使用SVC管理使用者介面來啟用資料收集。

====




== 父序號說明

傳統上Insight能夠報告儲存陣列序號或個別儲存節點序號。不過、有些儲存陣列架構並未完全符合此要求。SVC叢集可由1-4個應用裝置組成、每個應用裝置有2個節點。如果應用裝置本身有序號、則該序號既不是叢集的序號、也不是節點的序號。

儲存節點物件上的「父序號」屬性、會在個別節點位於僅屬於大型叢集一部分的中繼應用裝置/機箱內時、適當地填入IBM SVC陣列。



== 組態

|===


| *欄位* | *說明* 


 a| 
叢集IP
 a| 
SVC儲存設備完整網域名稱的IP位址



 a| 
選擇「密碼」或「OpenSSH金鑰檔」以指定認證類型
 a| 
用於透過SSH連線至裝置的認證類型



 a| 
庫存使用者名稱
 a| 
SVC CLI的使用者名稱



 a| 
庫存密碼
 a| 
SVC CLI的密碼



 a| 
完整的庫存私密金鑰路徑
 a| 
Inventory Private Key檔案的完整路徑



 a| 
效能使用者名稱
 a| 
用於收集效能的SVC CLI使用者名稱



 a| 
效能密碼
 a| 
用於收集效能的SVC CLI密碼



 a| 
效能私密金鑰的完整路徑
 a| 
效能私密金鑰檔案的完整路徑

|===


== 進階組態

|===


| *欄位* | *說明* 


 a| 
庫存輪詢時間間隔（分鐘）
 a| 
庫存輪詢之間的時間間隔（預設為40分鐘）



 a| 
排除裝置
 a| 
要從庫存集合中排除的裝置ID清單、以逗號分隔



 a| 
SSH程序等待逾時（秒）
 a| 
SSH程序逾時（預設值為200秒）



 a| 
效能意見調查時間間隔（秒）
 a| 
效能輪詢之間的時間間隔（預設為300秒）



 a| 
效能排除裝置
 a| 
要從效能集合中排除的裝置ID清單、以逗號分隔



 a| 
效能SSH程序等待逾時（秒）
 a| 
SSH程序逾時（預設值為200秒）



 a| 
清除傾印的統計資料檔案
 a| 
選取以清除傾印的統計資料檔案

|===