---
permalink: config-admin/ibm-powervm-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM PowerVM（SSH）資料來源會收集在由硬體管理主控台（HMC）管理的IBM Power硬體執行個體上執行的虛擬分割區相關資訊。對於組態、此資料來源需要使用者名稱才能透過SSH登入HMC、以及HMC組態的檢視層級權限。 
---
= IBM PowerVM資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM PowerVM（SSH）資料來源會收集在由硬體管理主控台（HMC）管理的IBM Power硬體執行個體上執行的虛擬分割區相關資訊。對於組態、此資料來源需要使用者名稱才能透過SSH登入HMC、以及HMC組態的檢視層級權限。



== 術語

從IBM PowerVM資料來源取得下列庫存資訊OnCommand Insight 。對於Insight取得的每種資產類型、都會顯示此資產最常用的術語。檢視或疑難排解此資料來源時、請謹記下列術語：

|===


| 廠商/模型術語 | Insight術語 


 a| 
hdisk
 a| 
虛擬磁碟



 a| 
託管系統
 a| 
主機



 a| 
LPAR、VIO伺服器
 a| 
虛擬機器



 a| 
Volume群組
 a| 
資料儲存區



 a| 
實體Volume
 a| 
LUN

|===
[NOTE]
====
這些只是通用的術語對應、可能不代表此資料來源的每個案例。

====


== 需求

* 硬體管理主控台（HMC）的IP位址
* 使用者名稱和密碼、可透過SSH存取HMC
* 連接埠需求SSH-22
* 檢視所有管理系統和邏輯分割安全性網域的權限
+
使用者也必須擁有HMC組態的「檢視」權限、以及收集HMC主控台安全性群組的VPD資訊的能力。使用者也必須能夠在「邏輯分割區」安全性群組下存取「虛擬IO伺服器命令」。最佳做法是從操作員角色開始、然後移除所有角色。HMC上的唯讀使用者沒有在AIX主機上執行代理命令的權限。

* IBM最佳實務做法是由兩個以上的HMC監控裝置。請注意、這可能會導致OnCommand Insight 無法回報重複的裝置、因此強烈建議您將備援裝置新增至此資料收集器的「進階組態」中的「排除裝置」清單。




== 組態

|===


| *欄位* | *說明* 


 a| 
硬體管理主控台（HMC）位址
 a| 
PowerVM硬體管理主控台的IP位址或完整網域名稱



 a| 
HMC使用者
 a| 
硬體管理主控台的使用者名稱



 a| 
密碼
 a| 
硬體管理主控台使用的密碼

|===


== 進階組態

|===


| *欄位* | *說明* 


 a| 
庫存輪詢時間間隔（分鐘）
 a| 
庫存輪詢之間的時間間隔（預設為20分鐘）



 a| 
SSH連接埠
 a| 
用於SSH至PowerVM的連接埠



 a| 
SSH程序等待逾時（秒）
 a| 
SSH程序逾時（預設為600秒）



 a| 
重試次數
 a| 
嘗試進行庫存重試的次數



 a| 
排除裝置
 a| 
以逗號分隔的裝置ID清單或要排除的顯示名稱

|===