---
permalink: config-admin/ibm-ds-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM DS（CLI）資料來源僅支援DS6xxx和DS8xxx裝置。NetApp E系列資料來源支援DS3xxx、DS4xxx和DS5xxx裝置。如需支援的機型和韌體版本、請參閱Insight資料來源支援對照表。 
---
= IBM DS資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM DS（CLI）資料來源僅支援DS6xxx和DS8xxx裝置。NetApp E系列資料來源支援DS3xxx、DS4xxx和DS5xxx裝置。如需支援的機型和韌體版本、請參閱Insight資料來源支援對照表。



== 術語

從IBM DS資料來源取得下列庫存資訊OnCommand Insight 。對於Insight取得的每種資產類型、都會顯示此資產最常用的術語。檢視或疑難排解此資料來源時、請謹記下列術語：

|===


| 廠商/模型術語 | Insight術語 


 a| 
磁碟機模組
 a| 
磁碟



 a| 
儲存映像
 a| 
儲存設備



 a| 
範圍集區
 a| 
儲存資源池



 a| 
固定區塊Volume
 a| 
Volume

|===
[NOTE]
====
這些只是通用的術語對應、可能不代表此資料來源的每個案例。

====


== 需求

* 每個DS陣列的IP位址
* 儲存設備顯示名稱為選用項目、僅供外觀使用
* 每個DS陣列上的唯讀使用者名稱和密碼
* 安裝在Insight伺服器上的協力廠商軟體：IBM dscli
* 存取驗證：執行 `dscli` 使用使用者名稱和密碼的命令
* 連接埠需求：80、443和750




== 組態

|===


| 欄位 | 說明 


 a| 
DS儲存設備
 a| 
DS儲存主機的IP位址或完整網域名稱



 a| 
使用者名稱
 a| 
用於DS CLI的名稱



 a| 
密碼
 a| 
用於DS CLI的密碼



 a| 
執行檔dscli.exe路徑
 a| 
的完整路徑 ``dscli.exe``公用程式：

|===


== 進階組態

|===


| 欄位 | 說明 


 a| 
庫存輪詢時間間隔（分鐘）
 a| 
庫存輪詢之間的時間間隔（預設為40分鐘）



 a| 
儲存設備顯示名稱
 a| 
IBM DS儲存陣列名稱



 a| 
庫存排除裝置
 a| 
要從庫存集合中排除的裝置序號清單、以逗號分隔



 a| 
效能意見調查時間間隔（秒）
 a| 
效能輪詢之間的時間間隔（預設為300秒）



 a| 
效能篩選器類型
 a| 
包括：僅從清單上的裝置收集資料。排除：不會從這些裝置收集資料



 a| 
效能篩選器裝置清單
 a| 
要納入或排除在效能集合之外的裝置ID清單、以逗號分隔

|===