---
permalink: config-admin/importing-and-exporting-user-data.html 
sidebar: sidebar 
keywords:  
summary: 匯入和匯出功能可讓您將註釋、註釋規則、查詢、效能原則和自訂儀表板匯出至一個檔案。此檔案可匯入至不同OnCommand Insight 的伺服器。 
---
= 匯入及匯出使用者資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
匯入和匯出功能可讓您將註釋、註釋規則、查詢、效能原則和自訂儀表板匯出至一個檔案。此檔案可匯入至不同OnCommand Insight 的伺服器。

只有在執行相同版本OnCommand Insight 的伺服器之間才支援匯出和匯入功能。

若要匯出或匯入使用者資料、請按一下*管理*並選取*設定*、然後選擇*匯入/匯出使用者資料*索引標籤。

在匯入作業期間、會根據匯入的物件和物件類型、新增、合併或取代資料。

* 註釋類型
+
** 如果目標系統中不存在名稱相同的註釋、請新增註釋。
** 如果註釋類型為清單、則會合併註釋、且目標系統中存在名稱相同的註釋。
** 如果註釋類型不是清單、且目標系統中存在名稱相同的註釋、則會取代註釋。


+
[NOTE]
====
如果目標系統中存在名稱相同但類型不同的附註、則匯入會失敗。如果物件取決於失敗的附註、這些物件可能會顯示不正確或不想要的資訊。匯入作業完成後、您必須檢查所有註釋相依性。

====
* 註釋規則
+
** 如果目標系統中不存在名稱相同的註釋規則、請新增註釋規則。
** 如果目標系統中存在名稱相同的註釋規則、則會取代註釋規則。


+
[NOTE]
====
註釋規則取決於查詢和註釋。匯入作業完成後、您必須檢查所有註釋規則的準確度。

====
* 原則
+
** 如果目標系統中不存在名稱相同的原則、請新增原則。
** 如果目標系統中存在名稱相同的原則、則會取代原則。


+
[NOTE]
====
匯入作業完成後、原則可能會不正常。匯入後、您必須檢查原則順序。如果註釋不正確、則相依於註釋的原則可能會失敗。您必須在匯入後檢查所有註釋相依性。

+

====
* 查詢
+
** 如果目標系統中不存在名稱相同的查詢、則新增查詢。
** 如果目標系統中存在名稱相同的查詢、即使查詢的資源類型不同、也會取代查詢。


+
[NOTE]
====
如果查詢的資源類型不同、則在匯入之後、使用該查詢的任何儀表板小工具都可能顯示不必要或不正確的結果。匯入後、您必須檢查所有查詢型Widget的準確度。如果註釋不正確、則相依於註釋的查詢可能會失敗。您必須在匯入後檢查所有註釋相依性。

+

====
* 儀表板
+
** 如果目標系統中不存在名稱相同的儀表板、請新增儀表板。
** 如果目標系統中存在名稱相同的儀表板、即使查詢的資源類型不同、也會取代儀表板。


+
[NOTE]
====
匯入後、您必須檢查儀表板中所有查詢型Widget的準確度。如果來源伺服器有多個名稱相同的儀表板、則會全部匯出。不過、只有第一個會匯入目標伺服器。為了避免在匯入期間發生錯誤、您應該在匯出儀表板之前、先確定其名稱是唯一的。

+

====

