---
permalink: config-admin/importing-data-sources-from-a-spreadsheet.html 
sidebar: sidebar 
keywords:  
summary: 您可以從OnCommand Insight 試算表將多個資料來源匯入到支援功能。如果您已在試算表中維護探索裝置、這可能很有幫助。此程序會新增資料來源、但無法用來更新現有的資料來源。 
---
= 從試算表匯入資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從OnCommand Insight 試算表將多個資料來源匯入到支援功能。如果您已在試算表中維護探索裝置、這可能很有幫助。此程序會新增資料來源、但無法用來更新現有的資料來源。



== 關於這項工作

包含試算表、可協助您建立資料來源OnCommand Insight 。此試算表具有下列屬性：

* 試算表可搭配Microsoft Excel 2003或更新版本使用。
* 每個索引標籤都有一種資料來源類型、例如Brocade SSE/CLI。
* 每一列代表要建立的新資料來源執行個體。


試算表包含一個巨集、可在OnCommand Insight 功能表中建立新的資料來源。



== 步驟

. 在中找到試算表 `<install_directory>/SANscreen/acq/bin/acqcli/SiteSurvey_DataSourceImporter_w_Macro.zip`。
. 在試算表中、以色彩在儲存格中輸入資料來源資訊。
. 刪除空白列。
. 從試算表執行 `CreateDataSources` 建立資料來源的巨集。
. 當系統提示您輸入認證時、請輸入OnCommand Insight 支援伺服器的管理使用者名稱和密碼。
+
結果會記錄在擷取記錄中。

. 系統會出現提示、詢問目前執行巨集的機器是否OnCommand Insight 已安裝。
+
選取下列其中一項：

+
** 否：如果要建立批次檔、且必須在OnCommand Insight 該機器上執行、請選取「否」。從安裝目錄執行此批次檔。
** 是：如果OnCommand Insight 已經安裝了此功能、請選取「是」、而且不需要其他步驟來產生資料來源資訊。


. 若要驗證新增的資料來源、請在瀏覽器中開啟Insight。
. 在Insight工具列上、按一下*管理*。
. 檢查您匯入的資料來源清單。

