---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: 安全性管理工具可讓您管理本機擷取使用者（Lau）的安全性選項。安全管理包括管理金鑰和密碼、儲存及還原您建立的安全組態、或將組態還原為預設設定。 
---
= 管理本地採購單位的安全性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `securityadmin` 此工具可讓您管理本機擷取使用者（Lau）的安全選項。安全管理包括管理金鑰和密碼、儲存及還原您建立的安全組態、或將組態還原為預設設定。



== 開始之前

您必須擁有 `admin` 執行安全組態工作的權限。



== 關於這項工作

您可以使用 `securityadmin` 管理安全性的工具：

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`




== 步驟

. 遠端登入Insight伺服器。
. 以互動模式（-I）啟動安全管理工具。
+
系統會要求登入認證資料。

. 輸入具有「admin」認證的帳戶使用者名稱和密碼。
. 選取*本機擷取單位*以重新設定本機擷取單位安全性組態。
+
畫面會顯示下列選項：

+
** *備份*
+
建立包含所有密碼和金鑰的資料保險箱備份壓縮檔、並將檔案放置在使用者指定的位置、或是下列預設位置：

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** *還原*
+
還原所建立之資料保存庫的壓縮備份。還原之後、所有密碼和金鑰都會還原為建立備份時的現有值。

+
[NOTE]
====
還原可用於同步多個伺服器上的密碼和金鑰、例如：-變更Lau上的加密金鑰-建立資料庫備份-將資料庫備份還原至每個Raus

+

====
** *變更加密金鑰*
+
變更用於加密或解密裝置密碼的AU加密金鑰。

+
[NOTE]
====
變更加密金鑰時、您應該備份新的安全性組態、以便在升級或安裝之後還原。

====
** *更新密碼*
+
變更「擷取」使用者帳戶的密碼。

+
[NOTE]
====
有些帳戶需要在密碼變更時進行同步處理。例如、如果您變更伺服器上「擷取」使用者的密碼、則需要變更劉、Rau和DWH上「擷取」使用者的密碼以進行比對。此外、當您變更密碼時、也應該備份新的安全組態、以便在升級或安裝之後還原。

====
** *重設為預設值*
+
將擷取使用者密碼和擷取使用者加密金鑰重設為預設值、預設值為安裝期間提供的值。

** *退出*
+
結束 `securityadmin` 工具：



. 選擇您要設定的選項、然後依照提示進行。

