---
permalink: config-admin/managing-security-on-the-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 安全性管理工具可讓您管理資料倉儲伺服器上的安全性選項。安全管理包括更新DWH伺服器上內部使用者的內部密碼、建立安全組態備份、或將組態還原為預設設定。 
---
= 管理資料倉儲的安全性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `securityadmin` 工具可讓您管理資料倉儲伺服器上的安全選項。安全管理包括更新DWH伺服器上內部使用者的內部密碼、建立安全組態備份、或將組態還原為預設設定。



== 關於這項工作

您可以使用 `securityadmin` 管理安全性的工具：

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`




== 步驟

. 遠端登入資料倉儲伺服器。
. 以互動模式啟動安全管理工具：
+
** Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i`
** Linux - `/bin/oci-securityadmin.sh -i`
+
系統會要求登入認證資料。



. 輸入具有「admin」認證的帳戶使用者名稱和密碼。
+
系統會顯示資料倉儲的安全管理功能表：

+
** *備份*
+
建立包含所有密碼和金鑰的資料保險箱備份壓縮檔、並將檔案放置在使用者指定的位置、或是預設位置：

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** *還原*
+
還原所建立之資料保存庫的壓縮備份。還原之後、所有密碼和金鑰都會還原為建立備份時的現有值。

+
[NOTE]
====
還原可用於同步多個伺服器上的密碼和金鑰、例如：-變更一部伺服器上的加密金鑰-建立資料庫備份-將資料庫備份還原至第二部伺服器

+

====
** *變更加密金鑰*
+
變更用於加密或解密密碼的DWH加密金鑰、例如連接器密碼和SMPT密碼。

** *更新密碼*
+
變更特定使用者帳戶的密碼。

+
*** 內部_
*** 併購
*** Cogns_admin
*** dwh
*** dwh_internal
*** dwhuser
*** 主機
*** 庫存
*** 根




+
[NOTE]
====
當您變更dwhuser、hosts、inventory或root密碼時、您可以選擇使用SHA-256密碼雜湊。此選項需要所有存取帳戶的用戶端都使用SSL連線。

====
+
** *重設為預設值*
+
將加密金鑰和密碼重設為預設值。預設值為安裝期間提供的值。

** *退出*
+
結束 `securityadmin` 工具：




