---
permalink: config-admin/metric-definitions.html 
sidebar: sidebar 
keywords:  
summary: 資產頁面的「專家檢視」區段會根據為資產選取的時間週期、顯示數個指標。每個指標都會顯示在自己的效能圖表中。您可以根據想要查看的資料、從圖表中新增或移除指標和相關資產。 
---
= Expert View度量定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資產頁面的「專家檢視」區段會根據為資產選取的時間週期、顯示數個指標。每個指標都會顯示在自己的效能圖表中。您可以根據想要查看的資料、從圖表中新增或移除指標和相關資產。

|===


| 度量 | 說明 


 a| 
寬帶零接收器、傳輸器
 a| 
在取樣期間、接收/傳輸緩衝區對緩衝區信用數轉換為零的次數。此度量代表連接埠因此連接埠超出信用額度而必須停止傳輸的次數。



 a| 
BB積分零持續時間Tx
 a| 
取樣時間間隔內、傳輸寬頻點數為零的時間（以毫秒為單位）。



 a| 
快取命中率（總計、讀取、寫入）%
 a| 
導致快取命中的要求百分比。點擊次數比存取磁碟區的次數越多、效能就越好。對於不收集快取命中率資訊的儲存陣列、此欄為空白。



 a| 
快取使用率（總計）%
 a| 
導致快取命中的快取要求總數百分比



 a| 
類別3捨棄
 a| 
3級光纖通道資料傳輸捨棄的計數。



 a| 
CPU使用率（總計）%
 a| 
作用中使用的CPU資源量、佔總可用（所有虛擬CPU）的百分比。



 a| 
crc錯誤
 a| 
在取樣期間、連接埠偵測到具有無效循環備援檢查（CRC）的框架數



 a| 
影格速率
 a| 
以每秒影格數（FPS）傳輸影格速率



 a| 
平均影格大小（接收、傳輸）
 a| 
流量與影格大小的比率。此度量可讓您識別網路中是否有任何高負荷框架。



 a| 
影格大小太長
 a| 
光纖通道資料傳輸框架過長的計數。



 a| 
影格大小太短
 a| 
光纖通道資料傳輸框架過短的計數。



 a| 
I/O密度（總、讀取、寫入）
 a| 
IOPS的數目除以Volume、內部Volume或Storage元素的已用容量（從最近的資料來源庫存輪詢中取得）。測量單位為每TB每秒I/O作業數。



 a| 
IOPS（總計、讀取、寫入）
 a| 
透過I/O通道傳遞的讀寫I/O服務要求數、或是每單位時間（以每秒I/O數為單位）該通道的一部分。



 a| 
IP處理量（總計、讀取、寫入）
 a| 
總計：傳輸和接收IP資料的彙總速率、單位為每秒MB。讀取：IP傳輸量（接收）：接收IP資料的平均速率、以百萬位元組/秒為單位。

寫入：IP傳輸量（傳輸）：傳輸IP資料的平均速率、以百萬位元組/秒為單位。



 a| 
延遲（總計、讀取、寫入）
 a| 
延遲（R&W）：資料在固定時間內讀取或寫入虛擬機器的速率。此值的測量單位為每秒百萬位元組。

延遲：資料儲存區中虛擬機器的平均回應時間。

最高延遲：資料儲存區中虛擬機器的最高回應時間。



 a| 
連結失敗
 a| 
連接埠在取樣期間偵測到的連結故障數。



 a| 
連結重設接收器、傳輸
 a| 
取樣期間的接收或傳輸連結重設次數。此度量表示連接埠對此連接埠發出的連結重設次數。



 a| 
記憶體使用率（總計）%
 a| 
主機使用的記憶體臨界值。



 a| 
部分右/右（總計）%
 a| 
一般而言、讀寫作業跨越RAID 5、RAID 1/0或RAID 0 LUN中任何磁碟模組的等量磁碟區界限的總次數、因為每個磁碟區交叉點都需要額外的I/O、所以這種情況並不有利低百分比表示有效率的等量磁碟區元素大小、表示磁碟區（或NetApp LUN）的對齊方式不正確。

對於CLARiiON、此值是等量磁碟區交叉數除以IOPS總數。



 a| 
連接埠錯誤
 a| 
取樣期間/指定時間範圍內的連接埠錯誤報告。



 a| 
訊號遺失計數
 a| 
訊號遺失錯誤數。如果發生訊號遺失錯誤、表示沒有電子連線、而且存在實體問題。



 a| 
交換率（總速率、輸入速率、輸出速率）
 a| 
取樣期間、記憶體從磁碟換入、移出或兩者都換入作用中記憶體的速率。此計數器適用於虛擬機器。



 a| 
同步遺失計數
 a| 
同步遺失錯誤數。如果發生同步遺失錯誤、硬體就無法判斷流量或鎖定流量。所有設備可能使用的資料速率不同、或光纖或實體連線品質不佳。每次發生此類錯誤後、連接埠都必須重新同步、這會影響系統效能。測量單位：kb/sec



 a| 
處理量（總計、讀取、寫入）
 a| 
在回應I/O服務要求時、資料在固定時間內傳輸、接收或兩者的速率（以每秒MB為單位）。



 a| 
捨棄框架逾時- Tx
 a| 
因逾時而捨棄的傳輸框架數。



 a| 
流量（總計、讀取、寫入）
 a| 
在取樣期間傳輸、接收或同時接收的流量、以每秒百萬位元組為單位。



 a| 
流量使用率（總計、讀取、寫入）
 a| 
取樣期間接收/傳輸/總流量與接收/傳輸/總容量的比率。



 a| 
使用率（總計、讀取、寫入）%
 a| 
傳輸（傳輸）和接收（接收）所用的可用頻寬百分比。



 a| 
寫入擱置中（總計）
 a| 
擱置中的寫入I/O服務要求數。

|===