---
permalink: config-admin/microsoft-azure-compute-data-source.html 
sidebar: sidebar 
keywords:  
summary: Insights使用Azure運算資料收集器從Azure運算執行個體取得庫存和效能資料OnCommand 。 
---
= Microsoft Azure運算資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Insights使用Azure運算資料收集器從Azure運算執行個體取得庫存和效能資料OnCommand 。



== 需求

您需要下列資訊來設定此資料收集器：

* 連接埠需求：443 HTTPS
* Azure管理REST IP（management.azure.com）
* Azure服務主要應用程式（用戶端）ID（使用者帳戶）
* Azure服務主要驗證金鑰（使用者密碼）


您必須設定Azure帳戶才能進行Insight探索。一旦帳戶設定正確、且您已在Azure中註冊應用程式、您將擁有使用Insight探索Azure執行個體所需的認證資料。下列連結說明如何設定帳戶以進行探索：https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal



== 組態

根據下表、將資料輸入資料來源欄位：

|===


| 欄位 | 說明 


 a| 
Azure服務主要應用程式（用戶端）ID（需具備讀取器角色）
 a| 
Azure的登入ID。需要讀取器角色存取權。



 a| 
Azure租戶ID
 a| 
Microsoft租戶ID



 a| 
Azure服務主要驗證金鑰
 a| 
登入驗證金鑰



 a| 
我瞭解Microsoft向我索取API要求
 a| 
請勾選此選項、確認您瞭解Microsoft會針對Insight Polling所提出的API要求向您提出帳單。

|===


== 進階組態

根據下表、將資料輸入資料來源欄位：

|===


| 欄位 | 說明 


 a| 
庫存輪詢時間間隔（分鐘）
 a| 
預設值為60



 a| 
選擇「排除」或「包含」以套用至依標記篩選虛擬機器
 a| 
指定在收集資料時、是否要加入或排除VM的by Tags。如果選取「include'」、則「標記金鑰」欄位不可為空白。



 a| 
標記要篩選虛擬機器的金鑰和值
 a| 
按一下「*+ Filter Tag*（*+篩選標籤*）」、選擇要納入/排除的VM（及相關磁碟）、方法是篩選符合VM上標籤的機碼和值。標記金鑰為必填、標記值為選用項目。當標記值為空白時、只要VM符合標記金鑰、就會進行篩選。



 a| 
效能意見調查時間間隔（秒）|
 a| 
預設值為300

|===