---
permalink: config-admin/monitoring-oncommand-insight-system-health.html 
sidebar: sidebar 
keywords:  
summary: 您應該定期查看健全狀況頁面、查看Insight系統元件的目前狀態、該頁面會顯示每個元件的狀態、並在發生問題時發出警示。 
---
= 監控OnCommand Insight 系統健全狀況
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該定期查看健全狀況頁面、查看Insight系統元件的目前狀態、該頁面會顯示每個元件的狀態、並在發生問題時發出警示。



== 步驟

. 登入InsightWeb UI。
. 按一下「*管理*」、然後選取「*健全狀況*」。
+
隨即顯示「健全狀況」頁面。

. 在「*詳細資料*」欄中、檢視特別注意任何注意狀態的元件目前狀態摘要、此欄前面會出現一個紅色圓圈、指出需要您立即注意的問題。
+
「健全狀況」頁面會根據您的系統組態、顯示下列任何或所有Insight元件的相關資訊：

+
|===


| 元件 | 測試 | 詳細資料 | 顯示 


 a| 
併購
 a| 
庫存資料處理
 a| 
本地擷取單位的狀態
 a| 
如果並行輪詢資料來源數量少於執行集區上限的75%（預設上限為30）、則會顯示「OK」（確定）。若使用量大於75%、則「擷取作業正忙」、並建議增加輪詢時間間隔或新增更多遠端擷取單位。



 a| 
DWH
 a| 
備份
 a| 
資料倉儲排程備份的狀態
 a| 
若啟用DWH排程備份、「OK」和上次成功的DWH備份時間。否則、會顯示任何發現錯誤的相關資訊。



 a| 
DWH
 a| 
ETL
 a| 
資料倉儲ETL狀態
 a| 
如果沒有錯誤、「OK」和上次成功的DWH建置時間。否則、會顯示任何發現錯誤的相關資訊。



 a| 
伺服器
 a| 
ASUP
 a| 
ASUP狀態
 a| 
「已啟用ASUP」、以及上次成功的在家時間（若有）。如果已啟用電話主選項、但遇到問題、則會顯示「ASUP故障」。

+"備份目錄無效"。

+顯示上次成功的電話回覆時間、以及上次失敗嘗試的時間（若有）。

+「ASUP已停用」（如果電話主選項已停用）。



 a| 
伺服器
 a| 
自動解析
 a| 
自動裝置解析狀態
 a| 
如果沒有錯誤、請選擇「OK」。如果識別錯誤導致無法解決問題、則會出現「Auto resolution is blocked」（自動解決已遭封鎖）。

+「低成功率」、如果能識別出低於75%的一般裝置。



 a| 
伺服器
 a| 
彈性搜尋
 a| 
彈性搜尋資料儲存區的狀態
 a| 
如果沒有錯誤、請選擇「OK」。如果無法連線至彈性搜尋服務、則「服務無法使用」。

+「偵測到叢集模式」（如果偵測到多個節點）。

+"高記憶體使用率"（如果使用的堆空間超過85%）。

+"狀態：紅色"表示彈性搜尋報告的錯誤。顯示錯誤的相關資訊、並建議聯絡客戶支援部門。



 a| 
伺服器
 a| 
CPU
 a| 
深入瞭解CPU使用率
 a| 
如果CPU負載低於65%、則為「OK」。「系統CPU負載很高。減少CPU負載。」 如果CPU負載大於65%。



 a| 
伺服器
 a| 
磁碟空間
 a| 
磁碟空間狀態
 a| 
釋放磁碟空間、Insight使用中的磁碟空間、以及Insight所保留的建議磁碟空間。如果磁碟使用率超過80%、則會顯示「低磁碟空間」。



 a| 
伺服器
 a| 
事件匯流排
 a| 
事件匯流排的狀態
 a| 
如果事件匯流排佇列為空白、則「'EventBus is Empty'」（事件匯流排為空白）、否則會顯示事件匯流排佇列的狀態。



 a| 
伺服器
 a| 
庫存資料處理
 a| 
Insight伺服器庫存資料處理功能的狀態
 a| 
若Insight伺服器不忙碌、則為「OK」。如果伺服器在最後一個小時內至少有75%的時間處於忙碌狀態、則會顯示「伺服器忙碌中」。建議不要新增更多資料來源、並建議將環境分割至多個伺服器。



 a| 
伺服器
 a| 
MySQL
 a| 
MySQL資料庫的狀態
 a| 
若未偵測到問題、則為「OK」。「資料庫的效能問題。有些查詢的執行時間過長」（如果查詢速度緩慢超過5%）。

+「資料庫記錄檔在<size> 過去一小時成長超過了不只是單純的資料而已。如果錯誤日誌增長到20 KB以上、請查看MySQL記錄檔。



 a| 
伺服器
 a| 
效能歸檔
 a| 
效能歸檔的狀態
 a| 
「效能歸檔已啟用」或「效能歸檔未啟用」。



 a| 
伺服器
 a| 
實體記憶體
 a| 
實體記憶體的狀態
 a| 
如果記憶體使用率低於85%、則為「OK」。「我的使用量很高、如果記憶體使用率超過85%、則可減少整體記憶體佔用空間、以確保系統穩定性。



 a| 
伺服器
 a| 
Service Pack
 a| 
Service Pack可用度
 a| 
顯示Service Pack是否可供Insight使用。如果有可用的Service Pack、則會顯示指示。



 a| 
伺服器
 a| 
使用資訊
 a| 
傳送使用資訊的狀態
 a| 
顯示是否已啟用或停用傳送使用資訊給NetApp。建議停用時啟用。顯示上次嘗試或上次成功的傳送時間。

+顯示所遇到問題的相關資訊。



 a| 
伺服器
 a| 
違規
 a| 
未處理違規的狀態
 a| 
若未處理的違規數量少於違規上限的75%、則為「OK」。如果未處理的違規數量超過違規上限的75%、則「允許的最大未決違規數是<number> 指不允許的數量。」建議檢閱效能原則組態。

+「違規管理程式已封鎖」（如果未處理的違規數量達到違規上限）。

+請注意、違規管理程式無法建立新的違規、建議您檢閱效能原則組態。



 a| 
伺服器
 a| 
每週備份
 a| 
每週備份狀態
 a| 
如果啟用每週備份、「'OK'」會顯示「每週備份未啟用」。

|===

