---
permalink: config-admin/netapp-host-and-vm-filesystems-data-source.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用NetApp主機和VM檔案系統資料來源、擷取所有Microsoft Windows主機和VM（虛擬機器）檔案系統的檔案系統詳細資料和儲存資源對應、以及所有支援的Linux VM（僅限虛擬對應的VM）。 已存在於Insight伺服器中、並以已設定的運算資源群組（CRG\）進行註釋。 
---
= NetApp主機與VM檔案系統資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用NetApp主機和VM檔案系統資料來源、擷取所有Microsoft Windows主機和VM（虛擬機器）檔案系統、以及所有支援的Linux VM（僅限虛擬對應的VM）的檔案系統詳細資料和儲存資源對應。 已存在於Insight伺服器中、並以已設定的運算資源群組（CRG）進行註釋。



== 一般要求

* 此功能必須另行購買。
+
如需協助、請聯絡Insight代表。

* 您應該查看Insight支援對照表、確認您的主機或虛擬機器作業系統是否受到支援。
+
若要驗證是否已建立檔案系統與儲存資源之間的連結、請檢查相關的儲存設備或虛擬化廠商類型與版本是否報告所需的磁碟區或虛擬磁碟識別資料。





== Microsoft Windows需求

* 此資料來源使用視窗管理規範（WMI）資料結構來擷取資料。
+
此服務必須可從遠端運作且可供使用。尤其是、連接埠135必須可存取、而且如果位於防火牆後、必須開啟連接埠135。

* Windows網域使用者必須擁有適當的權限才能存取WMI結構。
* 需要系統管理員權限。
* 動態TCP連接埠指派1024-6555、適用於Windows 2003及更舊版本
* 適用於Windows 2008的連接埠49152-6555


[NOTE]
====
一般而言、當您嘗試在Insight、AU及此資料來源之間使用防火牆時、應諮詢Microsoft團隊、以識別他們認為需要的連接埠。

====


== Linux需求

* 此資料來源使用安全Shell（SSH）連線在Linux VM上執行命令。
+
SSH服務必須可從遠端運作且可供使用。尤其是連接埠22必須可存取、而且如果在防火牆後必須開啟。

* SSH使用者必須擁有Sudo權限、才能在Linux VM上執行唯讀命令。
+
您必須使用相同的密碼登入SSH、並回答任何的Sudo密碼挑戰。





== 使用建議

* 您應該使用相同的運算資源群組註釋、註釋一組具有通用作業系統認證的主機和虛擬機器。
+
每個群組都有此資料來源的執行個體、可從這些主機和虛擬機器探索檔案系統詳細資料。

* 如果您有這個資料來源的執行個體成功率低（例如OnCommand Insight 、在1000部主機和群組中的虛擬機器中、僅有50部主機和虛擬機器會發現檔案系統詳細資料）、 您應該將成功探索的主機和虛擬機器移至個別的運算資源群組。




== 組態

|===


| 欄位 | 說明 


 a| 
使用者名稱
 a| 
作業系統使用者擁有適當權限、可為Windows作業系統使用者擷取檔案系統資料、其中必須包含網域首碼。



 a| 
密碼
 a| 
作業系統使用者的密碼



 a| 
運算資源群組
 a| 
用於標記資料來源主機和虛擬機器的註釋值會探索檔案系統。空白值表示資料來源會探索所有主機和虛擬機器的檔案系統、而這些主機和虛擬機器目前未註釋任何運算資源群組。

|===


== 進階組態

|===


| 欄位 | 說明 


 a| 
庫存輪詢時間間隔（分鐘）
 a| 
庫存輪詢之間的時間間隔（預設為360分鐘）

|===