---
permalink: config-admin/netapp-data-ontap-operating-in-7-mode-data-source.html 
sidebar: sidebar 
keywords:  
summary: 若儲存系統使用Data ONTAP 以7-Mode運作的VMware軟體、您應該使用ONTAPI資料來源、該資料來源會使用CLI取得容量編號。 
---
= NetApp Data ONTAP 支援7-Mode資料來源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若儲存系統使用Data ONTAP 以7-Mode運作的VMware軟體、您應該使用ONTAPI資料來源、該資料來源會使用CLI取得容量編號。



== 術語

從NetApp供應的NetApp解決方案7-Mode資料來源取得下列庫存資訊Data ONTAP OnCommand Insight 。對於Insight取得的每種資產類型、都會顯示此資產最常用的術語。檢視或疑難排解此資料來源時、請謹記下列術語：

|===


| 廠商/模型術語 | Insight術語 


 a| 
磁碟
 a| 
磁碟



 a| 
RAID群組
 a| 
磁碟群組



 a| 
檔案管理器
 a| 
儲存設備



 a| 
檔案管理器
 a| 
儲存節點



 a| 
Aggregate
 a| 
儲存資源池



 a| 
LUN
 a| 
Volume



 a| 
Volume
 a| 
內部Volume

|===
[NOTE]
====
這些只是通用的術語對應、可能不代表此資料來源的每個案例。

====


== 需求

* 靜態儲存控制器和FAS 合作夥伴的IP位址
* 連接埠443
* 控制器和合作夥伴的使用者名稱和密碼
* 控制器和合作夥伴控制器的自訂管理層級使用者名稱和密碼、具有7-Mode的下列角色功能：
+
** 「API-*」：使用此選項可OnCommand Insight 讓效益管理程式執行所有NetApp儲存API命令。
** 「login-http-admin」：使用此選項可透過OnCommand Insight HTTP連線至NetApp儲存設備。
** 「安全性-API-vFilerTM」：使用此功能可OnCommand Insight 讓效益管理系統執行NetApp儲存API命令、以擷取vFiler單元資訊。
** 「CLI選項」：使用此選項可讀取儲存系統選項。
** 「CLI/LUN」：存取這些命令來管理LUN。顯示特定LUN或LUN類別的狀態（LUN路徑、大小、線上/離線狀態及共用狀態）。
** "CLI/df"：使用此選項可顯示可用磁碟空間。
** "CLI/ifconfig"：使用此選項可顯示介面和IP位址。






== 組態

|===


| *欄位* | *說明* 


 a| 
Filer位址
 a| 
NetApp Filer的IP位址或完整網域名稱



 a| 
使用者名稱
 a| 
NetApp Filer的使用者名稱



 a| 
密碼
 a| 
NetApp Filer的密碼



 a| 
叢集中HA合作夥伴Filer的位址
 a| 
HA合作夥伴Filer的IP位址或完整網域名稱



 a| 
叢集中HA合作夥伴Filer的使用者名稱
 a| 
NetApp HA合作夥伴Filer的使用者名稱



 a| 
叢集中HA合作夥伴Filer的密碼
 a| 
NetApp HA合作夥伴Filer的密碼

|===


== 進階組態

|===


| *欄位* | *說明* 


 a| 
庫存輪詢時間間隔（分鐘）
 a| 
庫存輪詢之間的時間間隔（預設為20分鐘）



 a| 
連線類型
 a| 
選擇連線類型



 a| 
連線連接埠
 a| 
用於NetApp API的連接埠



 a| 
效能意見調查時間間隔（秒）
 a| 
效能輪詢之間的時間間隔（預設為300秒）

|===


== 儲存系統連線

除了使用此資料來源的預設管理使用者之外、您也可以直接在NetApp儲存系統上設定具有管理權限的使用者、以便此資料來源從NetApp儲存系統取得資料。

連線至NetApp儲存系統時、需要在取得主pFiler（儲存系統所在）時指定的使用者符合下列條件：

* 使用者必須位於vfiler0（根Filer/pFiler0）上。
+
擷取主要pFiler時、會擷取儲存系統。

* 下列命令定義使用者角色功能：
+
** 「API-*」：使用此選項可OnCommand Insight 讓效益管理程式執行所有NetApp儲存API命令。使用ZAPI時需要使用此命令。
** 「login-http-admin」：使用此選項可透過OnCommand Insight HTTP連線至NetApp儲存設備。使用ZAPI時需要使用此命令。
** 「安全性-API-vFilerTM」：使用此功能可OnCommand Insight 讓效益管理系統執行NetApp儲存API命令、以擷取vFiler單元資訊。
** 「CLI選項」：用於「選項」命令、用於合作夥伴IP和啟用的授權。
** 「CLI/LUN」：存取以下命令以管理LUN。顯示特定LUN或LUN類別的狀態（LUN路徑、大小、線上/離線狀態及共用狀態）。
** "CLI/df"：適用於"df -s"、"df -r"、"df -A -r"命令、用於顯示可用空間。
** "CLI/ifconfig"：用於執行「ifconfig-A」命令、用於取得檔案管理器IP位址。
** CLI字節：用於「rdfile /etc/netgroup」命令、用於取得netgroup。
** 「CLI/date」：適用於「date」命令、用於取得Snapshot複本的完整日期。
** 「CLCLI抓取」：適用於「快照清單」命令、可用於取得Snapshot複本。




如果未提供CLI日期或CLI快照權限、則擷取作業可以完成、但不會報告Snapshot複本。

若要成功取得7-Mode資料來源、且不會在儲存系統上產生任何警告、您應該使用下列其中一個命令字串來定義使用者角色。此處列出的第二個字串是第一個的精簡版本：

[listing]
----
login-http-admin,api-*,security-api-vfile,cli-rdfile,cli-options,cli-df,cli-lun,cli-ifconfig,cli-date,cli-snap,
or
login-http-admin,api-*,security-api-vfile,cli-*
----