---
permalink: config-admin/predefined-annotation-types.html 
sidebar: sidebar 
keywords:  
summary: OnCommandInsight提供一些預設註釋類型。這些附註可用來篩選或分組資料、以及篩選資料報告。 
---
= 預設註釋類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommandInsight提供一些預設註釋類型。這些附註可用來篩選或分組資料、以及篩選資料報告。

您可以將資產與預設註釋類型建立關聯、例如：

* 資產生命週期、例如生日、日出或生命週期結束
* 裝置的位置資訊、例如資料中心、建築物或樓層
* 資產分類、例如依品質（階層）、依連線裝置（交換器層級）或依服務層級分類
* 狀態、例如Hot（高使用率）


下表列出預設的註釋類型。您可以根據自己的需求、編輯這些註釋名稱中的任何一個。

|===


| 註釋類型 | 說明 | 類型 


 a| 
別名
 a| 
資源的使用者易記名稱。
 a| 
文字



 a| 
生日
 a| 
裝置上線或即將上線的日期。
 a| 
日期



 a| 
建置
 a| 
主機、儲存設備、交換器和磁帶資源的實體位置。
 a| 
清單



 a| 
城市
 a| 
主機、儲存設備、交換器和磁帶資源的市位置。
 a| 
清單



 a| 
運算資源群組
 a| 
主機和VM檔案系統資料來源所使用的群組指派。
 a| 
清單



 a| 
大陸
 a| 
主機、儲存設備、交換器和磁帶資源的地理位置。
 a| 
清單



 a| 
國家/地區
 a| 
主機、儲存設備、交換器和磁帶資源的國家位置。
 a| 
清單



 a| 
資料中心
 a| 
資源的實體位置、可用於主機、儲存陣列、交換器和磁帶。
 a| 
清單



 a| 
直接附加
 a| 
表示（是或否）儲存資源是否直接連線至主機。
 a| 
布林值



 a| 
生命週期終止
 a| 
裝置離線的日期、例如當租約過期或硬體即將淘汰時。
 a| 
日期



 a| 
網路別名
 a| 
使用者易記的Fabric名稱。
 a| 
文字



 a| 
現場
 a| 
裝置在建築物地板上的位置。可針對主機、儲存陣列、交換器和磁帶進行設定。
 a| 
清單



 a| 
熱
 a| 
已定期或在容量臨界值時大量使用的裝置。
 a| 
布林值



 a| 
附註
 a| 
您想要與資源相關聯的註解。
 a| 
文字



 a| 
機架
 a| 
資源所在的機架。
 a| 
文字



 a| 
空間
 a| 
在建築物內或主機、儲存設備、交換器和磁帶資源的其他位置。
 a| 
清單



 a| 
SAN
 a| 
網路的邏輯分割區。可用於主機、儲存陣列、磁帶、交換器及應用程式。
 a| 
清單



 a| 
服務層級
 a| 
一組可指派給資源的支援服務層級。提供內部磁碟區、qtree和磁碟區的排序選項清單。編輯服務層級以設定不同層級的效能原則。
 a| 
清單



 a| 
州/省
 a| 
資源所在的州或省。
 a| 
清單



 a| 
日落後
 a| 
設定的臨界值、在此之後無法對該裝置進行新的配置。適用於計畫性移轉和其他擱置中的網路變更。
 a| 
日期



 a| 
交換器層級
 a| 
包含預先定義的選項、可設定交換器類別。一般而言、這些名稱會保留在裝置的使用壽命內、但您可以視需要加以編輯。僅適用於交換器。
 a| 
清單



 a| 
層級
 a| 
可用於定義環境中的不同服務層級。階層可以定義層級類型、例如所需的速度（例如金級或銀級）。此功能僅適用於內部磁碟區、qtree、儲存陣列、儲存資源池和磁碟區。
 a| 
清單



 a| 
違規嚴重性
 a| 
在最高至最低重要性的階層中、排列違規（例如遺失主機連接埠或缺少備援）的等級（例如MAJOR）。
 a| 
清單

|===
[NOTE]
====
別名、資料中心、Hot、服務層級、 交換器層級、服務層級、層級和違規嚴重性為系統層級的附註、您無法刪除或重新命名；您只能變更其指派的值。

====