---
permalink: config-admin/scrubbing-data-for-transfer-to-support-webui.html 
sidebar: sidebar 
keywords:  
summary: 擁有安全環境的客戶需要與NetApp客戶服務部門溝通、以便在不影響資料庫資訊的情況下疑難排解所產生的問題。利用此功能、您可以OnCommand Insight 設定完整的關鍵字與模式字典、以便「清除」敏感資料、並將清理的檔案傳送給客戶支援部門。 
---
= 資料清理、以便傳輸至支援部門
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
擁有安全環境的客戶需要與NetApp客戶服務部門溝通、以便在不影響資料庫資訊的情況下疑難排解所產生的問題。利用此功能、您可以OnCommand Insight 設定完整的關鍵字與模式字典、以便「清除」敏感資料、並將清理的檔案傳送給客戶支援部門。



== 步驟

. 在Web UI中、按一下「*管理*」、然後選取「*疑難排解*」。
. 在頁面底部的「其他工作」區域中、按一下「*清理公用程式*」連結。
+
有幾個清理區段：在「Dictionary」、「清理資料」及「建置dictionary」、「Custom keywords」及「Regular Expressions」中查詢。

. 
+
.. 在「**在目錄中查詢」區段中、輸入要顯示其所取代值的程式碼、或輸入值以查看取代該程式碼的程式碼。附註：您必須先*建置*字典、才能從支援資料中找出要清理的值。


. 若要從支援資料新增您自己的關鍵字以清理、請在*自訂關鍵字*區段中、按一下功能表：動作[新增自訂關鍵字]。輸入關鍵字、然後按一下*「Save*（儲存*）」。關鍵字即會新增至該字典。
. 展開*模式（regexp）*。按一下「*新增*」以取得用於輸入新模式的對話方塊。
. 若要使用規則運算式來識別要清理的字詞或片語、請在*規則運算式*區段中輸入模式或模式。按一下功能表：「Actions（動作）」[「Add regular expression]（新增規則運算式）」、在欄位中輸入模式名稱和規則運算式、然後按一下「* Save（儲存）」。資訊已新增至該字典。
+
[NOTE]
====
模式必須包含圓括弧、以識別規則運算式擷取群組。

====
. 在「**Build D彙 編」一節中、按一下「*建置*」、即可開始編譯OnCommand Insight 從該資料庫中辨識為敏感的所有字詞。
+
完成後、您會看到提示、通知您有可用的修訂版字典。資料庫說明包含一行、指出該字典中有多少關鍵字。檢查您在字典中的關鍵字是否正確。如果您發現問題並想要重新建置該字典、請按一下資料庫區塊上的*重設*、從OnCommand Insight 該字典中移除從該資料庫收集的所有關鍵字。根據提示、不會刪除其他關鍵字。返回清理公用程式、然後再次輸入您的自訂關鍵字。

. 建立清理字典之後、您可以使用它來清理記錄、XML或其他文字檔、使資料成為匿名。
. 若要清理記錄檔、XML或其他文字檔、請在*清理資料*區段中、瀏覽找出檔案、然後按一下*清理檔案*。

