---
permalink: config-admin/setting-up-and-managing-user-accounts.html 
sidebar: sidebar 
keywords:  
summary: 使用者帳戶、使用者驗證和使用者授權、可透過兩種方式加以定義和管理：在Microsoft Active Directory（版本2或3）LDAP（輕量型目錄存取傳輸協定）伺服器、OnCommand Insight 或是在內部的還原使用者資料庫中。為每個人設定不同的使用者帳戶、可讓您控制存取權限、個人偏好設定和責任歸屬。請使用具有此作業管理員權限的帳戶。 
---
= 設定及管理使用者帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用者帳戶、使用者驗證和使用者授權、可透過兩種方式加以定義和管理：在Microsoft Active Directory（第2版或第3版）LDAP（輕量型目錄存取傳輸協定）伺服器、OnCommand Insight 或是在內部的非功能性使用者資料庫中。為每個人設定不同的使用者帳戶、可讓您控制存取權限、個人偏好設定和責任歸屬。請使用具有此作業管理員權限的帳戶。



== 開始之前

您必須完成下列工作：

* 安裝OnCommand Insight 您的不一樣授權。
* 為每位使用者分配唯一的使用者名稱。
* 確定要使用的密碼。
* 指派正確的使用者角色。


[NOTE]
====
安全性最佳實務做法要求系統管理員設定主機作業系統、以防止非系統管理員/標準使用者互動登入。

====


== 步驟

. 在瀏覽器中開啟Insight。
. 在Insight工具列上、按一下*管理*。
. 按一下*設定*。
. 選取「**使用者」索引標籤。
. 若要建立新的使用者、請按一下*「Actions」（動作）*按鈕、然後選取*「Add user*」（新增使用者*）。
+
您可以輸入*姓名*、*密碼*、*電子郵件*地址、然後選取其中一個使用者*角色*做為系統管理員、使用者或訪客。

. 若要變更使用者資訊、請從清單中選取使用者、然後按一下使用者說明右側的*編輯使用者帳戶*符號。
. 若要從OnCommand Insight 這個系統移除使用者、請從清單中選取使用者、然後按一下使用者說明右側的*刪除使用者帳戶*。




== 結果

當使用者登入OnCommand Insight 到NetApp時、伺服器會先嘗試透過LDAP驗證（如果已啟用LDAP）。如果OnCommand Insight 無法在LDAP伺服器上找到使用者、則會在本機Insight資料庫中搜尋。
