---
permalink: reporting/oncommand-insight-data-model-descriptions.html 
sidebar: sidebar 
keywords:  
summary: 包含數種資料模型、您可以從中選取預先定義的報告、或建立自己的自訂報告OnCommand Insight 。 
---
= 資料模型OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
包含數種資料模型、您可以從中選取預先定義的報告、或建立自己的自訂報告OnCommand Insight 。

每個資料模型都包含一個簡單的資料倉儲和一個進階的資料倉儲：

* 簡單的資料倉儲可讓您快速存取最常用的資料元素、而且只包含資料倉儲資料的最後一張快照、不含歷史資料。
* 進階資料倉儲可從簡單的資料倉儲中提供所有可用的值與詳細資料、並可存取歷史資料值。
* *容量資料模型*
+
可讓您回答有關儲存容量、檔案系統使用率、內部Volume容量、連接埠容量、qtree容量、 和虛擬機器（VM）容量。容量資料模型是多種容量資料模型的容器。您可以使用此資料模式建立報告、回答各種類型的問題：

+
** *儲存與儲存資源池容量資料模型*
+
可讓您回答有關儲存容量資源規劃的問題、包括儲存與儲存資源池、以及實體與虛擬儲存資源池資料。這種簡單的資料模式可協助您回答與現場容量有關的問題、以及隨著時間推移、各層級和資料中心的儲存資源池容量使用量。

+
如果您是容量報告的新手、您應該從這種資料模型開始著手、因為它是更簡單、目標明確的資料模型。您可以使用此資料模型回答類似下列的問題：

+
*** 達到80%實體儲存容量臨界值的預計日期為何？
*** 特定層級陣列的實體儲存容量為何？
*** 我的儲存容量是由製造商、產品系列以及資料中心提供？
*** 所有層級陣列的儲存使用率趨勢為何？
*** 使用率最高的前10大儲存系統為何？
*** 儲存資源池的儲存使用率趨勢為何？
*** 已配置多少容量？
*** 哪些容量可供分配？


** *檔案系統使用率資料模型*
+
可讓您回答有關檔案系統使用率的問題。此資料模型可讓您在檔案系統層級查看主機的容量使用率。系統管理員可決定每個檔案系統的分配和使用容量、判斷檔案系統類型、並根據檔案系統類型識別趨勢統計資料。您可以使用此資料模型回答下列問題：

+
*** 檔案系統的大小為何？
*** 資料存放在何處、以及如何存取、例如本機或SAN？
*** 檔案系統容量的歷史趨勢為何？因此、我們可以預期未來的需求為何？


** *內部Volume容量資料模型*
+
可讓您回答有關內部磁碟區已用容量、已分配容量及隨時間使用容量的問題：

+
*** 哪些內部磁碟區的使用率高於預先定義的臨界值？
*** 哪些內部磁碟區有可能因趨勢而耗盡容量？
*** 我們內部磁碟區的已用容量與已分配容量有何不同？


** *連接埠容量資料模型*
+
可讓您回答有關交換器連接埠連線、連接埠狀態和連接埠速度等問題。您可以回答下列類似問題、協助您規劃購買新交換器：

+
*** 如何建立可預測資源（連接埠）可用度的連接埠使用量預測（根據資料中心、交換器廠商和連接埠速度）？
*** 哪些連接埠可能會耗盡容量、提供資料速度、資料中心、廠商和主機與儲存連接埠數量？
*** 隨著時間推移、交換器連接埠容量趨勢為何？
*** 連接埠速度為何？
*** 需要哪種類型的連接埠容量、以及哪個組織即將耗盡特定的連接埠類型或廠商？
*** 購買該容量並提供該容量的最佳時機為何？


** * Qtree容量資料模型*
+
可讓您隨著時間而趨勢調整qtree使用率（使用量與分配容量等資料）。您可以依不同的維度來檢視資訊、例如依企業實體、應用程式、層級和服務層級來檢視。您可以使用此資料模型回答下列問題：

+
*** qtree的使用容量與每個應用程式或企業實體設定的限制有何不同？
*** 我們的使用量和可用容量有何趨勢、以便我們進行容量規劃？
*** 哪些企業實體使用的容量最多？
*** 哪些應用程式耗用的容量最多？


** * VM容量資料模型*
+
可讓您報告虛擬環境及其容量使用量。此資料模型可讓您針對VM和資料儲存區的容量使用量隨時間變化提出報告。資料模型也提供精簡配置和虛擬機器計費資料。

+
*** 如何根據虛擬機器和資料儲存區的資源配置來決定容量計費？
*** 哪些容量未被VM使用、哪些部分未使用是可用的、孤立的或其他的？
*** 根據消費趨勢、我們需要購買哪些產品？
*** 我使用儲存精簡配置和重複資料刪除技術、可省下多少儲存效率？VM容量資料模型中的容量是從虛擬磁碟（VMDK）取得。這表示使用VM容量資料模型的虛擬機器已配置大小是其虛擬磁碟的大小。這與OnCommand Insight 在VMware View中的虛擬機器已配置容量不同、後者會顯示VM本身的已配置容量。


** * Volume容量資料模型*
+
可讓您分析環境中磁碟區的所有層面、並依廠商、模型、層級、服務層級和資料中心來組織資料。您可以檢視與孤立磁碟區、未使用的磁碟區和保護磁碟區（用於複寫）相關的容量。您也可以看到不同的Volume技術（iSCSI或FC）、並針對陣列虛擬化問題、將虛擬磁碟區與非虛擬磁碟區進行比較。您可以使用此資料模型回答類似下列的問題：

+
*** 哪些磁碟區的使用率高於預先定義的臨界值？
*** 我的資料中心對於孤立Volume容量有何趨勢？
*** 我的資料中心容量有多少是虛擬化或精簡配置？
*** 我的資料中心容量必須保留多少才能進行複寫？




* *計費資料模式*
+
可讓您回答有關儲存資源（磁碟區、內部磁碟區和qtree）上已使用容量和已分配容量的問題。此資料模型可依主機、應用程式和企業實體提供儲存容量計費和責任資訊、同時包含目前和歷史資料。報告資料可依服務層級和儲存層進行分類。

+
您可以使用此資料模型來找出企業實體所使用的容量、以產生計費報告。此資料模式可讓您建立多種傳輸協定（包括NAS、SAN、FC和iSCSI）的統一報告。

+
** 對於沒有內部磁碟區的儲存設備、計費報告會顯示各磁碟區的計費。
** 對於具有內部磁碟區的儲存設備：
+
*** 如果將業務實體指派給磁碟區、計費報告會依磁碟區顯示計費。
*** 如果未將業務實體指派給磁碟區、但指派給qtree、則計費報告會顯示qtree的計費。
*** 如果未將業務實體指派給磁碟區且未指派給qtree、則計費報告會顯示內部磁碟區。
*** 決定是否依Volume、qtree或內部Volume顯示計費、是針對每個內部Volume進行、因此同一個儲存資源池中的不同內部Volume可以顯示不同層級的計費。容量資料會在預設時間間隔後清除。如需詳細資訊、請參閱資料倉儲程序。




+
使用「計費」資料模型的報告可能會顯示不同於使用「儲存容量」資料模型的報告值。

+
** 對於非NetApp儲存系統的儲存陣列、兩種資料模型的資料相同。
** 對於NetApp和Celerra儲存系統、Chargeback資料模型使用單一層（磁碟區、內部磁碟區或qtree）來計算費用、而儲存容量資料模型則使用多層（磁碟區和內部磁碟區）來計算費用。


* *庫存資料模型*
+
可讓您回答有關庫存資源的問題、包括主機、儲存系統、交換器、磁碟、磁帶、 qtree、配額、虛擬機器和伺服器、以及一般裝置。庫存資料模型包含數個子目標、可讓您檢視複製、FC路徑、iSCSI路徑、NFS路徑及違規等相關資訊。庫存資料模型不包含歷史資料。您可以回答此資料倉儲的問題包括：

+
** 我擁有哪些資產？這些資產在哪裡？
** 誰在使用這些資產？
** 我擁有哪些類型的裝置、以及這些裝置的元件為何？
** 每個作業系統有多少主機、這些主機上有多少連接埠？
** 每個資料中心中、每個廠商都有哪些儲存陣列？
** 每家廠商在每個資料中心有多少部交換器？
** 有多少連接埠未獲授權？
** 我們使用哪些廠商磁帶、以及每個磁帶上有多少連接埠？
** 在我們開始處理報告之前、是否已識別出所有的一般裝置？
** 主機與儲存磁碟區或磁帶之間有哪些路徑？
** 一般裝置與儲存磁碟區或磁帶之間的路徑為何？
** 每個資料中心有多少次違反每種類型的事件？
** 對於每個複寫的Volume、來源和目標磁碟區是什麼？
** 我的光纖通道主機HBA和交換器之間是否有任何韌體不相容或連接埠速度不相符的情形？


* *效能資料模型*
+
可讓您回答有關磁碟區、應用程式磁碟區、內部磁碟區、交換器、應用程式、 VM、VMDK、ESX與VM、主機和應用程式節點的比較。使用此資料模型、您可以建立報告來回答幾種效能管理問題：

+
** 在特定期間內、哪些磁碟區或內部磁碟區尚未使用或存取？
** 我們能否找出應用程式（未使用）儲存設備的任何可能設定錯誤？
** 應用程式的整體存取行為模式為何？
** 階層式磁碟區是否已適當指派給特定應用程式？
** 我們是否可以在不影響應用程式效能的情況下、為目前執行的應用程式使用更便宜的儲存設備？
** 哪些應用程式會對目前設定的儲存設備產生更多存取？使用交換器效能表時、您可以取得下列資訊：
** 我的主機流量是否透過連線的連接埠達到平衡？
** 哪些交換器或連接埠出現大量錯誤？
** 根據連接埠效能、最常使用的交換器有哪些？
** 根據連接埠效能、未充分利用的交換器有哪些？
** 根據連接埠效能、主機的處理量趨勢為何？
** 過去X天、某個指定主機、儲存系統、磁帶或交換器的效能使用率為何？
** 哪些裝置在特定交換器上產生流量（例如、哪些裝置負責使用高使用率交換器）？
** 我們環境中特定業務單位的處理量是多少？使用磁碟效能表時、您可以取得下列資訊：
** 根據磁碟效能資料、指定儲存資源池的處理量是多少？
** 使用率最高的儲存資源池為何？
** 特定儲存設備的平均磁碟使用率為何？
** 根據磁碟效能資料、儲存系統或儲存資源池的使用趨勢為何？
** 特定儲存資源池的磁碟使用量趨勢為何？使用VM和VMDK效能表時、您可以取得下列資訊：
** 我的虛擬環境效能是否最佳？
** 哪些VMDK報告的工作負載最高？
** 如何使用對應至不同資料存放區之VMD回報的效能、來做出重新分層的決策。效能資料模型包含的資訊可協助您判斷層級的適當性、應用程式的儲存設備組態錯誤、以及磁碟區和內部磁碟區的最後存取時間。此資料模型可提供回應時間、IOPs、處理量、待處理寫入次數及存取狀態等資料。


* *儲存效率資料模型*
+
可讓您追蹤一段時間內的儲存效率分數和潛力。此資料模型不僅會儲存已配置容量的測量值、也會儲存已使用或已使用的容量（實體測量值）。例如、啟用精簡配置時OnCommand Insight 、功能表功能表會顯示從裝置取得的容量。啟用重複資料刪除功能時、您也可以使用此模式來判斷效率。您可以使用儲存效率資料倉儲來回答各種問題：

+
** 因為實作精簡配置和重複資料刪除技術、我們的儲存效率可節省多少成本？
** 資料中心的儲存節約效益為何？
** 根據過去的容量趨勢、我們何時需要購買額外的儲存設備？
** 如果我們啟用精簡配置和重複資料刪除等技術、容量會增加多少？
** 關於儲存容量、我現在面臨風險嗎？



