---
permalink: reporting/reporting-user-roles.html 
sidebar: sidebar 
keywords:  
summary: 每個使用者帳戶都會被指派一組權限的角色。使用者數量受限於附加至每個角色的報告授權數量。 
---
= 報告使用者角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個使用者帳戶都會被指派一組權限的角色。使用者數量受限於附加至每個角色的報告授權數量。

每個角色均可執行下列動作：

* *收件者*
+
檢視OnCommand Insight 「報告入口網站」報告、並設定個人偏好設定、例如語言和時區的偏好設定。

+
[NOTE]
====
收件者無法建立報告、執行報告、排程報告、匯出報告、也無法執行管理工作。

====
* *商業消費者*
+
執行報告並執行所有收件者選項。

* *商業作者*
+
除了執行所有的商業消費者選項之外、還能檢視排程報告、互動執行報告、建立案例。

* *專業作者*
+
除了執行所有Business Author選項之外、還能建立報告、建立套件和資料模組。

* *系統管理員*
+
執行報告管理工作、例如匯入和匯出報告定義、設定報告、設定資料來源、以及關閉和重新啟動報告工作。



下表顯示每個角色所允許的權限和最大使用者數：

|===


| 功能 | 收件者 | 商業消費者 | 商業作者 | Pro作者 | 管理 


 a| 
在「團隊內容」索引標籤中檢視報告
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
執行報告
 a| 
否
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
排程報告
 a| 
否
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
上傳外部檔案
 a| 
否
 a| 
否
 a| 
是的
 a| 
是的
 a| 
否



 a| 
創造故事
 a| 
否
 a| 
否
 a| 
是的
 a| 
是的
 a| 
否



 a| 
建立報告
 a| 
否
 a| 
否
 a| 
否
 a| 
是的
 a| 
否



 a| 
建立套件與資料模組
 a| 
否
 a| 
否
 a| 
否
 a| 
是的
 a| 
否



 a| 
執行管理工作
 a| 
否
 a| 
否
 a| 
否
 a| 
否
 a| 
是的



 a| 
使用者人數
 a| 
使用者數量OnCommand Insight
 a| 
20
 a| 
2.
 a| 
1.
 a| 
1.

|===
當您新增資料倉儲與報告使用者時、如果您的角色超過限制、使用者就會新增為「已啟用」、您需要停用或移除具有該角色的其他使用者、以賦予新的使用者成員資格。

[NOTE]
====
報告撰寫功能需要Insight Plan授權。您可以購買arap（其他報告撰寫套件）來新增其他的Business Author和Pro作者使用者。如OnCommand Insight 需協助、請聯絡您的銷售代表。

====
這些報告使用者角色不會影響直接資料庫存取。這些報告使用者角色不會影響您使用資料集市建立SQL查詢的能力。
