---
permalink: reporting/which-report-answers-your-question.html 
sidebar: sidebar 
keywords:  
summary: 包含預先定義的報告、可因應多項常見的報告需求、提供重要的洞察力、讓利益相關者能夠針對其儲存基礎架構做出明智決策OnCommand Insight 。 
---
= 使用預先定義的報告來回答常見問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
包含預先定義的報告、可因應多項常見的報告需求、提供重要的洞察力、讓利益相關者能夠針對其儲存基礎架構做出明智決策OnCommand Insight 。

下列預先定義的報告可在*團隊內容*>*報告*或*團隊內容*>*廠商專屬報告*中取得。

NetApp Storage Automation Store可能提供更新版本的報告。您應定期查看Automation Store以取得報告。

* * AWS雲端成本資料*
+
雲端成本報告提供所有資產的整合檢視、讓您在環境中動態擴充雲端及內部部署服務時、能夠追蹤、分析及最佳化其使用率與成本。

+
此報告提供基礎架構與成本之間的關聯、提供清楚且可行的報告、透過集中的容量規劃和浪費偵測來確保適當規模。

* *應用程式服務層級容量與效能*
+
「應用程式服務層級容量與效能」報告提供應用程式的高層級總覽。您可以將此資訊用於容量規劃或移轉計畫。

* *計費*
+
「計費」報告提供主機、應用程式及企業實體的儲存容量計費與責任資訊、其中包含目前與歷史資料。

+
為了避免重複計算不包括ESX伺服器、請僅監控VM。

+
本報告的更新版本可從NetApp Storage Automation Store取得。

* *資料來源*
+
資料來源報告會顯示您站台上安裝的所有資料來源、資料來源狀態（成功/失敗）和狀態訊息。此報告提供資料來源疑難排解開始位置的相關資訊。失敗的資料來源會影響Insight報告的準確度、以及產品的一般使用性。

* * ESX與VM效能*的比較
+
ESX與VM效能報告提供ESX伺服器與VM的比較、顯示ESX伺服器與VM的平均與尖峰IOPs、處理量、延遲與使用率。若要避免重複計算、請排除ESX伺服器；僅包括VM。

+
本報告的更新版本可從NetApp Storage Automation Store取得。

* *架構摘要*
+
「Fabric摘要」報告可識別交換器和交換器資訊、包括連接埠數、韌體版本和授權狀態。報告不包含NPV交換器連接埠。

* *主機HBA*
+
主機HBA報告提供環境中主機的總覽、並提供HBA的廠商、機型和韌體版本、以及所連接之交換器的韌體層級。此報告可用於分析規劃交換器或HBA的韌體升級時的韌體相容性。

* *主機服務層級容量與效能*
+
「主機服務層級容量與效能」報告提供主機針對僅區塊應用程式的儲存使用率總覽。

* *主機摘要*
+
「主機摘要」報告提供每個所選主機的儲存使用率總覽、以及光纖通道和iSCSI主機的相關資訊。此報告可讓您比較連接埠和路徑、光纖通道和iSCSI容量、以及違規數。

* *授權詳細資料*
+
「授權詳細資料」報告會顯示您在所有擁有使用中授權的站台上、已獲授權的資源數量。此報告也會顯示所有具有作用中授權之站台的實際數量總和。總和可能包括由多個伺服器管理的儲存陣列重疊。

* *已對應但未遮罩的Volumes *
+
「已對應但未遮罩的Volume」（已對應但未遮罩的Volume）報告會列出其邏輯單元號碼（LUN）已對應供特定主機使用、但未遮罩至該主機的磁碟區。在某些情況下、這些LUN可能會停用已取消遮罩的LUN。任何主機都能存取未遮罩的Volume、使其容易遭受資料毀損。

* * NetApp容量與效能*
+
NetApp容量與效能報告提供已分配、已使用及已承諾容量的全球資料、並提供NetApp容量的趨勢與效能資料。

* * OCI Scorecor*
+
OCI Scorecard報告提供OnCommand Insight 由下列項目所發現之所有資產的摘要和一般狀態。狀態會以綠色、黃色和紅色旗標表示：

+
** 綠色表示正常情況
** 黃色表示環境中可能有問題
** 紅色表示需要注意的問題報告中的所有欄位都會在報告隨附的資料字典中說明。


* *儲存摘要*
+
「儲存摘要」報告提供原始、已分配、儲存資源池和磁碟區的已用及未使用容量資料的全域摘要。本報告概述所有探索到的儲存設備。

+
本報告的更新版本可從NetApp Storage Automation Store取得。

* *虛擬機器容量與效能*
+
說明虛擬機器（VM）環境及其容量使用量。必須啟用VM工具才能檢視某些資料、例如當VM關機時。

* * VM路徑*
+
VM Paths報告提供資料儲存容量資料和效能指標、以供虛擬機器在哪個主機上執行、哪些主機正在存取哪些共享磁碟區、哪些是作用中存取路徑、以及哪些是容量分配和使用量。

* *精簡集區的HDS容量*
+
HDS Capacity by Thin Pool報告會顯示精簡配置之儲存資源池上的可用容量量。

* * NetApp容量（依Aggregate）*
+
「NetApp容量（依集合體）」報告會顯示集合體的原始總計、總計、已使用、可用及已認可空間。

* *《Symmetrix Capacity by Thick Array*》
+
Symmetrix Capacity by Thick Array報告顯示原始容量、可用容量、可用容量、對應、遮罩、 以及總可用容量。

* *精簡集區的Symmetrix容量*
+
Symmetrix Capacity by Thin Pool報告會顯示原始容量、可用容量、已用容量、可用容量、已用百分比、 訂閱容量與訂閱率。

* * XIV陣列容量*
+
XIV Capacity by Array報告顯示陣列的已用和未使用容量。

* * XIV池容量*
+
XIV容量（依資源池）報告顯示儲存資源池的已用容量和未使用容量。


