---
permalink: install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html 
sidebar: sidebar 
keywords:  
summary: 安裝是獨立的、包含執行OnCommand Insight 和操作「恢復資料倉儲」（DWH\）和「報告」公用程式所需的元件。 
---
= 安裝OnCommand Insight 「資料倉儲與報告」
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝是獨立的、包含執行OnCommand Insight 和操作《支援資料倉儲》（DWH）和「報告」公用程式所需的元件。



== 開始之前

安裝或升級之前、請注意下列事項。

* 如果您要升級、請備份DWH。
* 您必須擁有本機的_Administrator _權限、才能安裝OnCommand Insight 含報告功能的「支援資料倉儲」。
* 確定已啟用Windows模組安裝程式服務（自動或手動）。
* 如果安裝在非C：磁碟機上、則必須啟用簡短檔案名稱。如果未啟用、安裝程式就會啟用它。
* 對於DB2元件、DB2使用者可以是_domain_使用者或_local_使用者。
+
** 如果DB2使用者是_網域_使用者、您必須擁有下列項目：
+
*** 「DB2使用者」必須已經建立、而且您必須知道使用者名稱和密碼
*** 身為安裝DWH with Reporting的使用者、您必須能夠查詢DB2使用者。您可以使用下列命令來驗證：
+
**** `net user <db2 user name> /domain`




** 如果「DB2使用者」是_本機_使用者、您必須具備下列條件：
+
*** 使用者的使用者名稱和密碼、以DB2使用者身分執行。如果此使用者不存在、安裝將會建立此使用者。


** [附註]




[]
====
DB2使用者名稱和Windows登入名稱具有下列限制：*有效字元為：「A」至「Z」；「A」至「z」；「0」至「9」；「#」；「@」； '_'；'!'；'('；')'；'{'； 「｝」；「-」；及「.」。*如果使用特殊字元「！」；「（」；「）」；「｛」；「｝」； '-'；及'.' 使用者名稱必須使用全部大寫字母。*字串中的第一個字元必須是字母字元@、#或$；不能是數字或字母順序_SYS_、_DBM_或_IBM_*、長度不得超過128個位元組。*不得為使用者、系統管理員、訪客、公共、本機或任何SQL保留字。

====
* DB2使用者不能與執行安裝的使用者相同。




== 步驟

. 使用具有管理員權限的帳戶登入資料倉儲伺服器。
. 下載Data Warehouse with Reporting .zip檔案、並將檔案解壓縮至安裝資料夾。
. 瀏覽至「_fesi\OCI <download location> 」、「wh安裝程式」資料夾、然後執行「_install」、OCI、「wh」、「bat_」指令碼。
+
[NOTE]
====
使用支援更新版本的版本、您必須執行指令碼才能正確安裝DWH/報告OnCommand Insight 。請勿執行.MSI安裝執行檔。

====
. 輸入DB2網域、或按Enter進入本機網域。
. 輸入DB2使用者名稱。如需使用者名稱限制、請參閱上述內容。
. 輸入DB2使用者的密碼。出現提示時、請重新輸入密碼。
. 輸入DB2元件的安裝路徑、或按Enter作為預設值。
. 系統會顯示您輸入的資訊。請仔細驗證所有設定。按Enter開始安裝。
. 如果出現提示、請允許Windows繼續進行DB2安裝。
. DB2安裝完成後、DWH安裝精靈將會執行。依照指示安裝DWH with Report.
+
安裝報告的資料倉儲可能需要一小時才能完成。


