---
permalink: install-windows/installation-prerequisites.html 
sidebar: sidebar 
keywords:  
summary: 在安裝OnCommand Insight 支援程式之前、您必須先下載目前的軟體版本、取得適當的授權、然後設定環境。 
---
= 安裝先決條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安裝OnCommand Insight 支援程式之前、您必須先下載目前的軟體版本、取得適當的授權、然後設定環境。

安裝OnCommand Insight 過程中、請先確認您具備下列條件：

* 下載安裝套件中針對目前版本的軟體檔案OnCommand Insight
* 操作下載OnCommand Insight 的版本的授權
* 最低的硬體與軟體環境
+
目前的產品可能會耗用其他硬體資源（因為OnCommand Insight 強化的功能性）、而OnCommand Insight 這些資源並未用於舊版的整合式功能。

* 部署計畫、包括OnCommand Insight 適用於「支援伺服器」、「資料倉儲與報告」、以及遠端擷取單元的硬體與網路組態。
* Java 8 OnCommand Insight for the Java UI。
+

NOTE: 包含Java SE 8的付費Oracle授權OnCommand Insight 。客戶不需要購買任何額外的Java SE 8授權。本授權涵蓋Java SE 8搭配所有OCI元件的使用。請參閱 link:legal-notices.html["通知"] 頁面以取得特定詳細資料。

* 已停用掃毒軟體
+
在OnCommand Insight 安裝過程中、您必須完全停用所有的掃毒程式。安裝之後、Insight元件（安裝、備份和歸檔程式路徑）所使用的路徑、除了排除整個路徑之外、還必須排除在掃毒範圍之外 `sanscreen` 掃描中的目錄。

+
此外、您也必須在安裝後、將IBM/DB2資料夾（例如_C:\Program Files\IBM\DB2_）排除在防毒掃描之外。



[NOTE]
====
如果您執行完整安裝以進行升級或移轉至新硬體、且現有系統包含非預設的安全性組態、則必須在執行安裝之前備份安全性組態。安裝完成後、您必須先還原安全組態、再還原伺服器（包括本機擷取單元）或資料倉儲資料庫。您必須先將安全組態還原至所有Insight伺服器、才能還原DWH資料庫。

若為就地升級（僅適用於Insight Server）、安全組態會妥善處理、您不需要還原。

您可以使用 `securityadmin` 建立組態備份及還原儲存組態的工具。如需詳細資訊、請搜尋 `securityadmin` 在VMware文件中心OnCommand Insight ： http://docs.netapp.com/oci-73/index.jsp[]

====