---
permalink: install-windows/overview-of-insight-upgrade-process.html 
sidebar: sidebar 
keywords:  
summary: 在您開始升級Insight之前、請務必瞭解升級程序。大多數Insight版本的升級程序都相同。 
---
= 概述此升級程序OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在您開始升級Insight之前、請務必瞭解升級程序。大多數Insight版本的升級程序都相同。

[NOTE]
====
* 升級 OnCommand Insight 之前、您必須備份資料保險箱 * 。

如需詳細資訊、請參閱link:../config-admin\/security-management.html["安全性管理工具"]指示。

====
Insight升級程序包括下列高層級工作：

* 正在下載安裝套件
* 備份資料倉儲資料庫
+
為了避免誤報資料、您必須在備份Insight資料庫之前備份Data倉儲資料庫。

* 備份Insight資料庫
+
Insight資料庫會在您執行就地升級時自動備份。最佳做法是在升級之前備份資料庫、並將備份放在Insight伺服器以外的位置。在升級過程中、Insight不會收集新資料。若要將未收集的資料量降至最低、您必須在計畫的升級時間內、於一或兩小時內開始資料庫備份。

* 如果組態已從預設組態變更、請備份資料倉儲和遠端擷取設備安全組態。
+
非預設的安全性組態必須在升級完成後、以及將資料倉儲資料庫還原至系統之前、還原至資料倉儲和Rau伺服器。

* 備份任何自訂資料倉儲報告
+
當您備份資料倉儲資料庫時、會包含自訂報告。備份檔案是在資料倉儲伺服器上建立。建議您將自訂報告備份到Data倉儲伺服器以外的位置。

* 如適用、請解除安裝Data倉儲和遠端擷取單元軟體
+
Insight伺服器有就地升級、您不需要解除安裝軟體。就地升級會備份資料庫、解除安裝軟體、安裝新版本、然後還原資料庫。

* 升級Insight伺服器、資料倉儲及遠端擷取設備上的軟體
+
所有先前套用的授權都會保留在登錄中；您不需要重新套用這些授權。

* 完成升級後的工作

