---
permalink: install-linux/anomaly-detection-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 異常偵測軟體需要特定的作業系統、記憶體容量、CPU核心和磁碟空間。您必須遵守特定要求、才能成功安裝異常偵測軟體。 
---
= 異常偵測需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
異常偵測軟體需要特定的作業系統、記憶體容量、CPU核心和磁碟空間。您必須遵守特定要求、才能成功安裝異常偵測軟體。

|===


| 元件 | 必要 


 a| 
作業系統
 a| 
執行下列其中一種授權版本的電腦、不執行其他應用程式層級的軟體：

* Red Hat Enterprise Linux 7.3、7.4、7.5、7.6、7.7、 7.8、7.9、8.1、8.2、8.3、 8.4、8.5
* CentOS 7.5、7.6、7.7、7.8、7.9、 CentOS 8串流
* Oracle Enterprise Linux 7.5、7.6、7.7、7.8、7.9、 8.1、8.2、8.3、8.4、8.5
* SUSE Enterprise Linux 15.1,15.2、15.3
* openSUSE 15.1、15.2、15.3


授權版本可確保作業系統自動解決安裝所需的相依性。

建議使用專屬伺服器。



 a| 
虛擬機器（VM）
 a| 
只要保留執行個體的CPU和記憶體資源、異常偵測就能在虛擬環境中執行。



 a| 
CPU與記憶體
 a| 
8核心。64 GB記憶體伺服器。



 a| 
可用磁碟空間
 a| 
伺服器需要200 GB的可用磁碟空間、磁碟空間分區如下：

* 150 GB英里 `/var/lib`
* 25 GB英里 `/var/log`
* 25 GB英里 `/opt`


軟體安裝需要下列磁碟空間：

* 5 GB英里 `/var/lib`
* 25 GB英里 `/var/log`
* 25 GB英里 `/opt`


這是安裝的最佳實務做法 ``/opt``和 在獨立於根檔案系統的磁碟上 (`/`）。



 a| 
權限
 a| 
需要Sudo權限才能安裝異常偵測軟體。



 a| 
網路
 a| 
您要安裝異常偵測軟體的Insight伺服器、必須與執行異常偵測引擎的伺服器位於同一個網路、或至少位於同一個站台或資料中心。異常偵測軟體不支援廣域網路（WAN）的組態設定。

TCP連接埠8080和9200必須在VM上開啟。



 a| 
先決條件
 a| 
您必須擁有有效的Perform授權。您必須擁有要安裝異常偵測軟體的Insight伺服器IP位址。

如果不接受預設連接埠、則Insight伺服器上必須有替代連接埠號碼。

TCP連接埠8080和9200必須在VM上開啟。

您必須擁有VM上具有管理員權限之帳戶的使用者名稱和密碼。

您必須輸入兩個反斜槓（company \使用者）作為使用者名稱、其中包含單一反斜槓（company \使用者）。

使用者名稱不可在反斜槓（company）後面加上「t」。

|===
[NOTE]
====
您必須與NetApp代表討論並驗證所有規模調整建議。

====