---
permalink: install-linux/data-warehouse-server-requirements-linux.html 
sidebar: sidebar 
keywords:  
summary: 資料倉儲伺服器必須在符合既有硬體與軟體需求的電腦上執行。您必須確保此機器上尚未安裝Apache Web伺服器或報告軟體。 
---
= 資料倉儲伺服器需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資料倉儲伺服器必須在符合既有硬體與軟體需求的電腦上執行。您必須確保此機器上尚未安裝Apache Web伺服器或報告軟體。

[NOTE]
====
針對功能需求調整規模OnCommand Insight 具有多種相依性、例如環境中的資產數量、保留的歷史資料量等。下列資料倉儲規模調整範例僅為準則、代表已測試Insight的部分環境。變更環境中的任何這些或其他因素、都可能改變Insight的規模調整需求。

====
建議在安裝或升級Insight之前、先聯絡您的銷售工程師以取得詳細的規模調整指導。

*範例：*

|===


| 環境因素： | 已測試的磁碟空間、CPU和記憶體： 


 a| 
18部儲存設備3、400部VM

4、500個交換器連接埠
 a| 
200 GB硬碟8核心

32 GB RAM



 a| 
110部儲存設備11、500部VM

14、500個交換器連接埠
 a| 
300 GB硬碟8核心

48 GB RAM

|===
*要求：*

|===


| 元件 | 必要 


 a| 
作業系統
 a| 
執行下列其中一種授權版本的電腦、不執行其他應用程式層級的軟體：

* Red Hat Enterprise Linux 7.9 、 8.10 、 9.4
* CentOS 8 Stream 、 CentOS 9 Stream
* Oracle Enterprise Linux 7.9 、 8.10 、 9.4




 a| 
虛擬機器（VM）
 a| 
只要保留執行個體的CPU和記憶體資源、此元件就能在虛擬環境中執行。



 a| 
CPU
 a| 
8 - 40個CPU核心



 a| 
記憶體
 a| 
32 GB - 2 TB RAM



 a| 
可用磁碟空間
 a| 
200 GB - 512 GB磁碟空間中至少應有50 GB的可用磁碟空間 `/var/lib` 中的分割區和25 GB可用磁碟空間 `/opt` 和 `/var/log` 分割區：



 a| 
網路
 a| 
* 100 Mbps或1 Gbps乙太網路連線
* 靜態IP位址
* 針對支援此功能的OnCommand Insight 支援流程、連接埠80、443、1098、1099、 3873、8083及4444至4446
* 適用於MySQL、連接埠3306


|===