---
permalink: install-linux/installing-an-ethernet-monitoring-unit-linux.html 
sidebar: sidebar 
keywords:  
summary: 「乙太網路監控單元（emus）會檢查您環境中的網路封包、以便針對從主機到儲存資源的網路流量、進行效能疑難排解。 
---
= 安裝乙太網路監控單元
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「乙太網路監控單元（emus）會檢查您環境中的網路封包、以便針對從主機到儲存資源的網路流量、進行效能疑難排解。



== 開始之前

[NOTE]
====
乙太網路監控單元（EMU）不支援OnCommand Insight 版本7.3.12及更新版本。

====
您必須已完成所有安裝先決條件。



== 步驟

. 使用具有Sudo權限的帳戶登入EMU伺服器。
. 瀏覽至安裝檔案所在伺服器上的目錄、然後輸入下列命令：
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`

+
其中 `<version>` 是您下載檔案名稱中指定的版本號碼。

. 您可以檢視的語法、命令引數及參數使用量 `oci-install.sh`：
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. 執行安裝指令碼：
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. 閱讀授權合約並接受。
. 回答每個提示：
+
** * OnCommand Insight 《伺服器名稱或IP位址*》-用於識別OnCommand Insight 該伺服器的主機名稱或IP位址。EMU使用此名稱/IP來開啟與伺服器的通訊連結。如果您指定主機名稱、請確定它可以透過DNS解析。
** *擷取單位名稱*-識別EMU的唯一名稱。
** *受保護的遠端擷取連接埠（HTTPS）*- EMU用來將環境變更資訊傳送至該伺服器的連接埠OnCommand Insight OnCommand Insight 。此設定應符合安裝OnCommand Insight 此伺服器時所輸入的值、且在所有emus上必須相同。
** *乙太網路PPA輸出目錄*-輸入PPA輸出資料夾。
** *要監控的乙太網路PA介面*-輸入您要監控其流量的介面。
** *啟用巨型封包*-如果客戶環境使用巨型封包、EMU會建立大型封包緩衝區來讀取這些封包。否則、EMU會將可用的記憶體資源池用於標準的乙太網路封包。在您回答所有提示之後、安裝將會開始、大約需要10分鐘、視安裝的應用程式而定。



