---
permalink: install-linux/installing-the-oncommand-insight-server-linux.html 
sidebar: sidebar 
keywords:  
summary: 使用命令列安裝支援OnCommand Insight 。 
---
= 安裝OnCommand Insight The功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用命令列安裝支援OnCommand Insight 。



== 開始之前

您必須已完成所有安裝先決條件。



== 步驟

. 使用具有Sudo權限的帳戶登入Insight伺服器。
. 瀏覽至安裝檔案所在伺服器上的目錄、然後輸入下列命令：
+
`unzip oci-<version>-linux-x86_64.zip`

+
請確定您已檢查安裝檔案的版本編號、版本編號可能與命令中所示的版本編號不同。

. 您可以檢視的語法、命令引數及參數使用量 `oci-install.sh` ：
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh --help`

. 執行安裝指令碼：
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh`

+
在 CentOS 9 Stream 、 Red Hat Enterprise Linux 9.4 或 Oracle Linux 9.4 上安裝 Insight Server 時、您必須先變更至包含安裝程式檔案的目錄、然後使用「 --install-mySQL 相依性」命令列選項來執行安裝命令：

+
....
cd /tmp/oci-7.3.16.1.297-linux-x86_64
sudo ./oci-install.sh --install-mysql-dependencies
....
. 請閱讀授權合約、接受並遵循提示進行。
. 如果您使用的是Insight Consumption授權模式、則必須啟用傳送使用資訊給NetApp的功能。輸入 `Y` 在這個提示下。




== 結果

在您回答所有提示之後、安裝將會開始、大約需要10分鐘、視安裝的應用程式而定。

. 如果您要安裝遠端擷取單元（ Rau ）、則必須執行 securityadmin Tool 、為 _Acquisition 使用者建立密碼。安裝 Rau 時需要使用此密碼。
+
附註：如果您已建立此密碼、則不需要如下所述同步伺服器和 Rau 。





== 將伺服器與 DWH 和 Rau 同步


IMPORTANT: 安裝遠端擷取單元和 / 或資料倉儲後、您 * 必須 * 將 Rau/DWH 與 OnCommand Insight 伺服器同步。請遵循下列步驟：

link:../install-windows/installing-a-remote-acquisition-unit-rau.html#synchronize-server-and-rau["同步伺服器與 Rau （ Windows ）"]

link:../install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html#synchronize-server-and-dwh["同步伺服器與 DWH （ Windows ）"]

link:../install-linux/installing-a-remote-acquisition-unit-rau-linux.html#synchronize-server-and-rau["同步伺服器與 Rau （ Linux ）"]

link:../install-linux/installing-oncommand-insight-data-warehouse-linux.html#synchronize-server-and-dwh["同步伺服器與 DWH （ Linux ）"]
