---
permalink: dwh/annotations.html 
sidebar: sidebar 
keywords:  
summary: 附註提供定義環境中物件相關資訊的方法、然後可讓您根據附註來追蹤物件。例如、您可以將建置或樓層編號註釋新增至環境中的裝置、然後建立查詢、以傳回資料中心一樓的所有裝置。 
---
= 您可以使用註釋執行的操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
附註提供定義環境中物件相關資訊的方法、然後可讓您根據附註來追蹤物件。例如、您可以將建置或樓層編號註釋新增至環境中的裝置、然後建立查詢、以傳回資料中心一樓的所有裝置。

此外、您可能想要查看特定資料中心或企業實體中的所有裝置、並判斷哪個企業實體使用的是最多層級1的儲存設備。若要這麼做、您可以使用OnCommand Insight Web UI將資料中心、企業實體或層級附註指派給裝置。然後、您可以將選定的使用者自訂註釋從OnCommand Insight 功能表中移入資料倉儲。您想要這麼做、才能看到指派給物件的註釋值會出現在自訂報告中。

您可以指定要將哪些使用者定義的註釋衍生至資料倉儲。附註會新增為額外的欄位至詳細目錄中的物件表格、以及資料集市中的相關維度表格。當您使用OnCommand Insight 「資源資訊」使用者介面更新資源註釋、並啟動或等待下一個「資料倉儲建置」時、您會在下列表格中看到結果：

* dwh_inventory.annotation_value
* dwh_inventory.object_to_dotannotation


若要確保OnCommand Insight 在資料倉儲中包含輸入的註釋、必須執行下列主要程序：

* 在您將註釋匯入資料倉儲之前、您必須先確保註釋已準備好OnCommand Insight 在物件中。
+
若要這麼做、您可以手動執行*疑難排解*>*強制更新資料倉儲註釋*選項、或等到下次排程的暫時性資料執行程序為止。當您強制更新註釋時、您會強制OnCommand Insight 支援還原伺服器計算暫態資料（例如註釋值）並將其放入資料庫表格、以便資料倉儲ETL程序能夠讀取資料。註釋資料每隔15分鐘會自動更新一次、不過您可以強制更新頻率更高。

* 然後使用 Data Warehouse ** Annotations** 選項將註釋導入 Data Warehouse 。
* 如果您想要在使用OnCommand Insight 《支援報告入口網站》報告撰寫工具所建立的報告中加入附註、您必須更新OnCommand Insight 《支援報告中繼資料模型》。


升級Data倉儲時、註釋工作會在資料庫還原程序期間自動執行。註釋工作也會在Wildfly啟動時自動執行。

[NOTE]
====
Wildfly是OnCommand Insight 一款應用程式伺服器、可執行各種功能的Java程式碼、OnCommand Insight 同時適用於支援支援此功能的伺服器和Data倉儲。

====