---
permalink: dwh/data-retention-and-time-periods.html 
sidebar: sidebar 
keywords:  
summary: 根據不同的資料集市和資料的時間精細度、資料倉儲會保留從擷取、轉換和載入（ETL\）程序取得的資料、以供不同的時間週期使用OnCommand Insight 。 
---
= 資料保留、ETL和時間週期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據資料的不同資料目標和時間精細度、資料倉儲會保留從擷取、轉換及載入（ETL）程序取得的資料、並在不同的時間週期內保留這些資料OnCommand Insight 。



== 磁碟區和內部磁碟區的效能目標和每小時精細度

《The Data倉儲》記錄14天內每小時（24個資料點）的平均時數、每小時上限和存取位元OnCommand Insight 。存取位元是布林值、如果存取磁碟區則為true、如果未在每小時間隔內存取磁碟區則為假。前一天的所有24個資料點都是在當天的第一個ETL程序中取得。

您不需要每小時執行一次ETL程序、就能收集每小時的資料點。白天執行其他ETL程序、並不會從OnCommand Insight VMware伺服器取得任何效能資訊。



== 磁碟區和內部磁碟區的效能目標和每日精細度

在每一天處理ETL時、前一天的每日平均值會計算並填入資料倉儲中。每日平均值是前一天24個資料點的摘要。效能資料會將每日摘要保留在磁碟區和內部磁碟區上13個月。



== 容量市場和每日精細度

容量市場每日為各種容量資料提供13個月的每日測量數據。資料倉儲中的容量資料是在ETL之前最後一次擷取裝置資料來源時的最新資料。



== 容量市場和每月精細度

資料倉儲會將每日容量資料保留13個月。在達到13個月的臨界值之後、容量資料會每月摘要一次。每月資料是以月代表日期所反映的值為基礎。

下表顯示每月摘要中包含哪些每月資料：

|===


| 日期 | 為月代表值 | 已分配容量 


 a| 
1月1日
 a| 
1（對）
 a| 
50 TB



 a| 
1月2日
 a| 
0（錯）
 a| 
52 TB



 a| 
...
 a| 
...
 a| 
...



 a| 
1月31日
 a| 
0（錯）
 a| 
65 TB



 a| 
2月1日
 a| 
1（對）
 a| 
65 TB

|===
根據表、每月報告顯示1月份的配置TB數為50 TB、2月份的配置TB數為65 TB。一月份的所有其他容量值將不會納入每月摘要。



== 庫存倉儲

庫存資料倉儲並非歷史資料倉儲。每次執行ETL程序時、會清除並重新建立Inventory mart。因此、從Inventory mart產生的任何報告都不會反映歷史庫存組態。
