---
permalink: dwh/restoring-and-upgrading-reports-for-versions-prior-to-6-3.html 
sidebar: sidebar 
keywords:  
summary: 如果您要升級早於6.3版的Insight版本、則必須手動還原報告成品。 
---
= 還原及升級6.3之前版本的報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您要升級早於6.3版的Insight版本、則必須手動還原報告成品。



== 開始之前

遵循「升級資料倉儲（DWH）」和「備份自訂報告及報告成品」主題中的指示。



== 步驟

. 若要從6.3版之前的版本還原報告成品、請複製您建立並儲存在中的匯出Backup.zip檔案 `<install>\cognos\c10_64\deployment` 目錄。
. 開啟瀏覽器並前往 `http://<server>:<port>/reporting` 用於安裝期間使用的伺服器和連接埠。
. 輸入您的使用者名稱和密碼、然後按一下*登入*。
. 從* Launch（啟動）*功能表中、選取* Insight報告管理*。
. 單擊 * Configuration （配置） * 選項卡。
+
由於資料模型發生變更、舊套件中的報告可能無法執行、需要升級。

. 按一下*內容管理*。
. 按一下「*新增匯入*」按鈕。
. 請確定您複製到部署目錄的歸檔（例如、 `backup6.0.zip`），然後單擊* Next*（下一步*）。
. 如果您輸入密碼來保護歸檔文件、請輸入密碼、然後按一下*確定*。
. 變更名稱 `+Export...+` 至 `Import Backup` 然後按一下*下一步*。
. 按一下每個套件名稱旁的鉛筆圖示、必要時輸入新的目標名稱。例如、新增 `_original` 現有名稱的後置。然後單擊*確定*。
. 重新命名所有套件的目標套件名稱之後、請選取所有藍色資料夾、然後按一下*「下一步*」繼續。
. 接受所有預設值。
. 按一下「*完成*」、然後選取「*執行*」。
. 請查看此匯入的詳細資料、然後按一下「*確定*」。
. 按一下「*重新整理*」以檢視匯入的狀態。
. 匯入完成後、按一下*關閉*。




== 結果

「公共資料夾」標籤會顯示兩組套件。例如、其中一個具有 `7.0` 後置詞（適用於較新版本）、以及一個字元（含） `_original` （或您在備份/還原程序中輸入的任何內容）後置字元、其中包含您的舊報告。由於資料模型發生變更、舊套件中的報告可能無法執行、需要升級。您的入口網站索引標籤現在指向目前版本的入口網站頁面。
