---
permalink: howto/configuring-applications-for-your-company.html 
sidebar: sidebar 
keywords:  
summary: 瞭解貴公司環境中使用的應用程式、有助於追蹤資產使用狀況、並報告成本。我們將在此設定貴公司的應用程式、並將其與適當的資產建立關聯。 
---
= 為貴公司設定應用程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解貴公司環境中所使用的應用程式、有助於追蹤資產使用狀況、並報告成本。我們將在此設定貴公司的應用程式、並將其與適當的資產建立關聯。



== 關於這項工作

在「為貴公司設定商業實體」區段中、我們建立了一些商業實體、並建議您列出與每個企業實體相關的所有應用程式。利用此功能、我們可以追蹤與這些應用程式相關的資料、例如使用量或成本報告OnCommand Insight 。

您必須先定義這些應用程式、並將其與適當的資產建立關聯、才能追蹤與環境中執行之應用程式相關的資料。您可以將應用程式與下列資產建立關聯：主機、虛擬機器、磁碟區、內部磁碟區、qtree、 共享區和Hypervisor。

在此逐步解說中、我們想要追蹤行銷團隊用於Exchange電子郵件的虛擬機器使用量。您會記得我們在定義業務實體時所建立的下表。我們將在這份工作表中新增一欄、列出每個企業實體所使用的應用程式。（此表格僅為工作表範例。您不會在Insight中的商業實體表中看到「應用程式」欄。）

|===


| 租戶 | 業務線 | 業務單位 | 專案 | 應用程式 


 a| 
NetApp
 a| 
資料儲存
 a| 
合法
 a| 
專利
 a| 
Oracle Identity Manager、Oracle on Demand、Patentowiz



 a| 
NetApp
 a| 
資料儲存
 a| 
行銷
 a| 
銷售活動
 a| 
Exchange、Oracle共享資料庫、Blastoff Event Planner



 a| 
不適用
 a| 
不適用
 a| 
安全性
 a| 
不適用
 a| 
不適用



 a| 
...
 a| 
 a| 
 a| 
 a| 

|===
*在Insight中建立應用程式：*



== 步驟

. 以具有管理權限的使用者身分登入Insight。
. 選擇*管理*>*應用程式*
. 按一下「*+附加*」按鈕
. 輸入應用程式名稱（例如輸入「'Exchange」）
. 選取應用程式的優先順序
. 如果您想要將應用程式與企業實體建立關聯、請從*企業實體*下拉式清單中選取一個。否則、您可以將其保留為「無」。
. 如果您想要確保每個主機都能存取叢集中的相同磁碟區、請確認已勾選*驗證磁碟區共用*方塊。例如、高可用度叢集中的主機通常需要遮罩至相同的磁碟區、才能進行容錯移轉；不過、不相關應用程式中的主機通常不需要存取相同的實體磁碟區。此外、為了安全起見、法規原則可能會要求您明確禁止不相關的應用程式存取相同的實體磁碟區。如果您不使用磁碟區共用、請清除*驗證磁碟區共用*方塊。這需要保證授權。
. 按一下儲存。
. 針對您環境中的所有其他應用程式重複上述步驟。




== 完成後

我們發現行銷團隊使用Exchange應用程式。我們想要查看他們的Exchange虛擬機器使用率、以便預測何時需要新增更多儲存設備。讓我們將Exchange應用程式與行銷部門的所有VM建立關聯。最簡單的方法是透過查詢來達成此目標。

依照這些步驟、您可以將每個應用程式與其適當的資產建立關聯。

*將應用程式與資產建立關聯：*

現在您已經建立應用程式（並視需要將應用程式綁定至商業實體）、我們現在可以將這些應用程式與您環境中的資產建立關聯。在此範例中、我們會將Exchange應用程式與貴公司的許多虛擬機器建立關聯。最簡單的方法就是查詢。

. 選取*查詢*>*+新查詢*。
. 在「*選取資源類型*」下拉式清單中、選擇「虛擬機器」
. 我們假設行銷團隊會使用字串「`_mktg_'」來命名他們的資產。在「Name filter（名稱篩選器）」方塊中、輸入「`_mktg_'（不含引號）」、然後按一下「Apply（apply）（套用（勾選）」按鈕。
. 顯示所有VM的「`_mktg_」字串清單。
. 如有需要、請按一下「*更多*」下拉式清單、然後新增其他篩選條件。
. 按一下每個所需VM名稱旁的核取方塊、選取用於Exchange的VM、或按一下欄頂端的核取方塊、以選取所有VM。
. 選取所需的VM後、按一下*「Actions」（動作）*按鈕、然後選擇「* Add Application*」（新增應用程式*）。
. 在「指派應用程式」對話方塊中、按一下「*應用程式*」下拉式清單、然後選取「'Exchange」。
. 按一下「 * 儲存 * 」。
. 視需要重複上述步驟、將Exchange應用程式與其他資產（主機、磁碟區等）建立關聯。

