---
permalink: howto/creating-policies-and-thresholds-for-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: 您可以建立觸發警示的效能原則、以便在超過儲存池資產的臨界值時通知您。 
---
= 為儲存資源池建立效能原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立觸發警示的效能原則、以便在超過儲存池資產的臨界值時通知您。



== 開始之前

此程序假設您已精簡配置儲存資源池。



== 關於這項工作

您想要建立可監控及報告儲存資源池中可能導致中斷運作的變更的原則。對於精簡配置的實體儲存資源池、您想要監控實體容量、並監控過度使用率。



== 步驟

. 在OnCommand Insight 瀏覽器中開啟
. 選擇*管理*>*效能原則*
+
隨即顯示「效能原則」頁面。原則會依物件組織、並依原則在清單中的顯示順序進行評估。如果啟用通知（*管理*>*通知*）、您可以設定Insight在違反效能原則時傳送電子郵件。

. 按一下「**+Add**」以建立新原則。
. 在*原則名稱*中輸入儲存資源池的原則名稱。
. 在*套用至類型*的物件中、選取儲存資源池。
. 在*「Apply after」（套用時間）*中輸入First實例。
. 在*嚴重性*中輸入「重大」
. 設定您要在臨界值違反時通知的電子郵件收件者。
+
根據預設、系統會將違反原則的電子郵件警示傳送給全域電子郵件清單中的收件者。您可以覆寫這些設定、以便將特定原則的警示傳送給特定的收件者。

+
按一下連結以開啟收件者清單、然後按一下+按鈕以新增收件者。此原則的違規警示將傳送給清單中的所有收件者。

. 在*建立警示中、如果下列任一項為真*、請輸入容量比率-已使用> 85%




== 結果

當使用超過85%的儲存資源池實體容量時、此組態會導致系統傳送重大警告訊息。使用100%的實體記憶體將導致應用程式故障。



== 建立其他儲存資源池原則



=== 關於這項工作

建立額外的「容量比率-已使用」原則、在使用的儲存資源池容量超過75%時發出警告訊息。如果啟用通知（*管理*>*通知*）、您可以設定Insight在違反效能原則時傳送電子郵件。
