---
permalink: howto/creating-a-performance-policy-for-alerting.html 
sidebar: sidebar 
keywords:  
summary: 效能原則可讓您在符合特定條件時監控及傳送警示。 
---
= 建立警示效能原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
效能原則可讓您在符合特定條件時監控及傳送警示。



== 關於這項工作

現在我們已經註釋過我們的資產、現在我們來建立效能原則、以便在Sunnyvale（DC1_SVL）資料中心的任何儲存陣列延遲超過2毫秒時發出警示。發生這些情況時、我們會傳送電子郵件給所選的收件者。



== 步驟

. 選擇*管理*>*效能原則*。
+
「效能原則」頁面隨即開啟。已設定數個預設原則、您可以根據需求進行修改。不過、我們會建立新的原則。

. 按一下「*+附加*」按鈕。
+
「*新增原則*」對話方塊隨即開啟。

. 在「*原則名稱*」欄位中、輸入「「資料中心延遲原則」。
+
您必須使用不同於物件所有其他原則名稱的名稱。例如、內部磁碟區不能有兩個名為「延遲」的原則；不過、內部磁碟區可以有「延遲」原則、而不同磁碟區則有另一個「延遲」原則。最佳實務做法是永遠為任何原則使用唯一名稱、無論物件類型為何。

. 對於*套用至類型*的物件、請選取* Storage *。
. 在「* with annotation *」（*附註*）欄位中、選取「* Data Center* is "'DC1_SVL"（或在此處選擇所需資料中心的名稱）。
. 在*第一次出現*的窗口之後應用。
+
第一次發生選項會在第一次資料樣本超過臨界值時觸發警示。當臨界值超過一次且持續超過指定時間、所有其他選項都會觸發警示。

. 從*嚴重性*清單中選取*警告*。
. 在*電子郵件收件者*下、按一下以覆寫全域收件者清單。按一下「**+*」以新增第一個所需警示收件者的電子郵件地址、然後按一下「*確定*」。針對任何其他想要的電子郵件收件者重複上述步驟。
. 如果下列*任一項為真、請保留「Create alert（建立警示）」的預設選項。如果達到任何一個設定臨界值、就會發出警示。您也可以選擇僅在*全部*符合設定臨界值時發出警示。
. 若要設定第一個臨界值、請在下拉式清單中選取*延遲-總計*、並將其設為大於2毫秒。
. 如有需要、請按一下*「Add threshold*（新增臨界值*）」按鈕、新增額外的臨界值以發出警示。當原則以您想要的方式自訂時、請按一下*「儲存*」。
. 如果產生警示、您也可以*停止處理其他原則*。如果符合此原則的條件、這將會停止其他原則警示。
. 您可以視需要新增任意數量的新原則、根據不同的業務需求、針對其他收件者設定警示。任何未設定特定收件者的原則、都會傳送警示至「*管理*>*通知*」頁面中設定的全域收件者清單




== 完成後

每個新原則都會在儲存時自動啟動、而且在符合原則條件時（稱為「_違 規」）、收件者也會開始收到警示。您也可以在*儀表板*>*違規儀表板*中監控這些違規行為。
