---
permalink: howto/custom-dashboard-roll-up.html 
sidebar: sidebar 
keywords:  
summary: 儀表板小工具中顯示的資料會從擷取的資料點彙總、讓儀表板具有靈活度和簡潔性。 
---
= 彙總與集合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儀表板小工具中顯示的資料會從擷取的資料點彙總、讓儀表板具有靈活度和簡潔性。

每個Widget中顯示的資料會從擷取期間收集的基礎資料點上彙總。例如、如果您有一個折線圖小工具顯示一段時間內的儲存IOPS、您可能會想要查看每個資料中心的獨立折線、以便快速比較。您可以選擇以下列其中一種方式來彙總此資料：

* *平均*：將每一行顯示為基礎資料的平均_。
* *最大*：將每一行顯示為基礎資料的最大_。
* *最小*：將每一行顯示為基礎資料的最小_。
* * Sum *：將每一行顯示為基礎資料的_sum_。


若要這麼做、請在您的小工具查詢中、先選擇資產類型（例如_Storage_）和度量（例如_IOPS - Tota_l）。對於*彙總*、請選擇彙總方法（例如_Avg_）、然後選取要用來彙總資料的屬性或註釋（例如、_Data Center_）。小工具會自動更新、並顯示每個資料中心的一行。

您也可以選擇將基礎資料的_all_彙總到圖表或表格中。在此案例中、您會在Widget中取得每個查詢的單一行、顯示所有基礎資產所選度量的平均值、最小值、最大值或總和。

如果您已設定查詢的篩選條件、則會根據篩選的資料來建立彙總的資料。

請注意、當您選擇依任何欄位（例如_Model_）彙總小工具時、仍需要*篩選依據*該欄位、才能在圖表或表格上正確顯示該欄位的資料。

*彙總資料：*您可以將資料點彙總成分鐘、小時或日等時段、以進一步調整時間序列圖（折線、區域等）、然後再依屬性（若已選擇）彙總資料。您可以選擇根據資料點的平均、最大、最小或總和、或根據所選時間間隔內收集的最後一個資料點來集合資料點。若要選擇集合體方法、請按一下小工具查詢區段中的*更多選項*。

允許的最小時間間隔為10分鐘。較短的時間間隔加上較長的時間範圍、可能會導致「集合時間間隔導致太多資料點」。 警告：如果時間間隔較短、而且儀表板時間範圍增加至7天、您可能會看到這一點。在這種情況下、Insight會將集合時間間隔暫時延長至1小時、直到您選取較短的時間範圍為止。

您也可以在長條圖小工具和單值小工具中彙總資料。

依預設、大部分的資產計數器會集合至_Avg_。某些計數器預設會彙總至_Max_、_min_或_Sum_。例如、連接埠錯誤會根據預設彙總至_Sum_、其中儲存IOPS會彙總至_Avg_。
