---
permalink: howto/custom-dashboard-concepts.html 
sidebar: sidebar 
keywords:  
summary: 自訂儀表板和小工具可讓您靈活地顯示資料。以下是一些概念、可協助您充分發揮自訂儀表板的效益。以下各節將詳細說明每個概念。 
---
= 自訂儀表板概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自訂儀表板和小工具可讓您靈活地顯示資料。以下是一些概念、可協助您充分發揮自訂儀表板的效益。以下各節將詳細說明每個概念。

*變數*

變數可讓您一次變更儀表板上部分或所有小工具中顯示的資料。將每個小工具設定為使用通用變數、在單一位置所做的變更會導致每個小工具中顯示的資料自動更新。

*多個查詢和（或）運算式*

每個時間序列小工具（折線、不規則曲線、區域或堆疊區域圖）最多可有五個查詢和（或）運算式來決定要顯示的資料、讓您在單一圖表上比較不同的資料集。例如、您可以使用折線圖來顯示儲存設備和虛擬機器的IOPS、或使用單一圖表來比較所有儲存集區的處理量和延遲。

*彙總與分組*

每個Widget中顯示的資料會從收集到的資料點彙總。您可以選擇以下列其中一種方式來彙總此資料：

* 平均：將資料捲動為基礎資料的平均值
* 最大：將資料聚集至最大基礎資料
* 最小：將資料捲動至最小基礎資料
* 總計：將資料彙總為基礎資料的總和


根據預設、所有基礎資料都會縮合到圖表或表格上的單一項目（全部）中。您可以選擇將特定屬性的資料彙總、例如資料中心或階層、將基礎資料分散到所需的群組。您的小工具只會顯示所選屬性的資料。

您可以根據所選的屬性、將表格小工具中的資料分組。例如、您可以選擇依資料中心將資料表分組。群組可以隨時展開或摺疊。表格中的效能資料會根據您在小工具中設定的彙總方法（平均值、最大值、最小值或總和）、在群組標頭中彙總。

表格小工具可依任何欄位排序、並可視需要移動或調整欄位大小。

*頂端/底端*

使用此選項可限制圖表小工具中的結果集、以選取是在小工具中顯示前N個結果、還是在後N個結果中顯示。當資料未被聚集或由特定屬性聚集時、您可以選擇此選項。

*置換儀表板時間*

根據預設、您新增至儀表板的大部分小工具會根據儀表板的時間範圍設定（3h、24h、3D、7d、30d或自訂範圍）來顯示資料。不過、您可以在個別小工具中覆寫此時間設定、強制它們在特定時間內容中顯示資料、無論儀表板的時間設定為何。

下一節將更詳細地說明這些概念。
