---
permalink: howto/expressions-example-read-iops-percentage.html 
sidebar: sidebar 
keywords:  
summary: 使用運算式、您可以使用替代方法來檢視度量、例如總計的百分比。 
---
= 運算式範例：讀取IOPS百分比
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用運算式、您可以使用替代方法來檢視度量、例如總計的百分比。



== 關於這項工作

在此範例中、我們要將讀取IOPS顯示為總IOPS的百分比。您可以將此視為下列公式：

* 讀取百分比=（讀取IOPS /總IOPS）x 100


此資料可顯示在儀表板的折線圖中。若要這麼做、請依照下列步驟進行：



== 步驟

. 建立新的儀表板、或在*編輯模式*中開啟現有的儀表板。
. 將小工具新增至儀表板。選擇*區域圖*。
+
小工具會以編輯模式開啟。根據預設、會顯示* Storage *資產的* IOPS -總計*查詢。如有需要、請選擇不同的資產類型。

. 按一下*「轉換成運算式*」按鈕。
+
目前的查詢會轉換成運算式模式。請注意、您無法在「運算式」模式中變更資產類型。請注意、當您處於「運算式」模式時、按鈕會變更為*恢復查詢*。如果您想隨時切換回查詢模式、請按一下此選項。請注意、切換模式會將欄位重設為預設值。

+
目前、請保持*運算式*模式。

. 「* IOPS -總計*」指標現在位於字母變數欄位「a」中。在「'b'」變數欄位中、按一下* Select *、然後選擇* IOPS - read*。
+
您可以在變數欄位後面按一下「**+**」按鈕、總共新增五個字母變數以供運算式使用。在我們的讀取百分比範例中、我們只需要IOPS總計（「a」）和IOPS讀取（「b」）。

. 在*運算式*欄位中、您可以使用每個變數對應的字母來建置運算式。我們知道_讀取百分比=（讀取IOPS /總IOPS）x 100_、因此我們將此運算式寫成： `(b / a) * 100`
. 「*標籤*」欄位可識別運算式。將標籤變更為「讀取百分比」、或是對您具有同等意義的內容。
. 將「*單位*」欄位變更為「`%'」或「'%'」。
+
此圖表顯示所選儲存裝置隨時間變化的IOPS讀取百分比。如果需要、您可以設定篩選器、或選擇不同的彙總方法。請注意、如果您選取* Sum *做為彙總方法、所有百分比值都會一起新增、可能會高於100%。

. 按一下「*儲存*」將圖表儲存至儀表板。
+
您也可以在*折線圖*、*不規則曲線圖*或*堆疊區域圖*小工具中使用運算式。


