---
permalink: howto/expressions-example-system-i-o.html 
sidebar: sidebar 
keywords:  
summary: 運算式可讓您自由記錄可從其他度量計算的資料。 
---
= 運算式範例：「系統」I/O
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
運算式可讓您自由記錄可從其他度量計算的資料。



== 關於這項工作

範例2：OnCommand Insight 從資料來源取得許多指標。其中包括讀取、寫入和總IOPS。然而、透過擷取所報告的IOPS總數有時會包括「系統」IOPS、這些IO作業並非資料讀取或寫入的直接部分。此系統I/O也可視為「例行性」I/O、這是正常系統作業所需的、但與資料作業並無直接關係。

若要顯示這些系統I/O、您可以從擷取報告的IOPS總計中減去讀取和寫入IOPS。公式可能如下所示：

* 系統IOPS =總IOPS（讀取IOPS +寫入IOPS）


然後、這些資料就會顯示在儀表板的折線圖中。若要這麼做、請依照下列步驟進行：



== 步驟

. 建立新的儀表板、或在*編輯模式*中開啟現有的儀表板。
. 將小工具新增至儀表板。選擇*折線圖*。
+
小工具會以編輯模式開啟。根據預設、會顯示* Storage *資產的* IOPS -總計*查詢。如有需要、請選擇不同的資產類型。

. 按一下按鈕以建立查詢複本。
+
查詢的複本會新增至原始資料下方。

. 在第二個查詢中、按一下「*轉換成運算式*」按鈕。
+
目前的查詢會轉換成運算式模式。如果您想隨時切換回查詢模式、請按一下*恢復查詢*。請注意、切換模式會將欄位重設為預設值。

+
目前、請保持*運算式*模式。

. 「* IOPS -總計*」指標現在位於字母變數欄位「a」中。按一下「* IOPS -總計*」、將其變更為「* IOPS -讀取*」。。
. 在「'b'」變數欄位中、按一下* Select *（選擇*）、然後選擇* IOPS - Write（寫入*）。
. 在*運算式*欄位中、您可以使用每個變數對應的字母來建置運算式。我們只會將自己的說法寫成： `a + b`。在「*顯示*」區段中、為此運算式選擇「**區域圖」。
. 「*標籤*」欄位可識別運算式。將標籤變更為「系統IOPS」、或是對您而言具有同等意義的項目。
+
此圖表會以折線圖形式顯示IOPS總計、並在區域圖下方顯示讀取和寫入IOPS的組合。兩者之間的落差顯示與資料讀取或寫入作業沒有直接關聯的IOPS。

. 按一下「*儲存*」將圖表儲存至儀表板。

