---
permalink: howto/how-to-troubleshoot-fibre-channel-bb-credit-0-errors.html 
sidebar: sidebar 
keywords:  
summary: Fibre Channel會使用緩衝區對緩衝區點數（BB點數）來控制傳輸流程。從連接埠傳送訊框時、信用值會減量、而當連接埠收到回應時、信用值會補貨。如果連接埠中的BB積分沒有補貨、傳輸流程可能會受到影響。連接埠需要記憶體或緩衝區、才能暫時儲存訊框、直到它們依序組裝及交付為止。緩衝區數是連接埠可以儲存的框架數、稱為緩衝區點數。 
---
= 疑難排解Fibre Channel寬頻點數0錯誤
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fibre Channel使用緩衝區對緩衝區的信用額度（寬頻信用額度）來控制傳輸流程。從連接埠傳送訊框時、信用值會減量、而當連接埠收到回應時、信用值會補貨。如果連接埠中的BB積分沒有補貨、傳輸流程可能會受到影響。連接埠需要記憶體或緩衝區、才能暫時儲存訊框、直到它們依序組裝及交付為止。緩衝區數是連接埠可以儲存的框架數、稱為緩衝區點數。

由於特定連接埠方法的可用點數為零、因此會出現錯誤、警告連接埠在達到零時停止接收傳輸、直到補充了BB點數才會繼續接收傳輸。

Insight效能原則可讓您設定下列連接埠度量的臨界值。

|===


 a| 
BB積分歸零- rx



 a| 
在取樣期間、接收緩衝到緩衝信用點數的轉換次數為零



 a| 
BB積分歸零- Tx



 a| 
在取樣期間、傳輸緩衝區對緩衝區信用數轉換為零的次數



 a| 
BB積分零-總計



 a| 
此連接埠因連接埠不足信用額度而必須停止傳輸的次數



 a| 
BB積分零持續時間- Tx



 a| 
取樣時間間隔內、傳輸寬頻點數為零的時間（以毫秒為單位）

|===
下列情況可能會導致BB Credit錯誤：

* 如果某個特定實作的FC框架的大小比例很高、明顯低於最大大小、則可能需要更多BB_點數。
* 工作負載會變更至環境、而可能影響連接至端口或裝置的工作負載、例如儲存節點。


您可以使用Fabric、交換器和連接埠資產頁面來監控光纖通道環境。連接埠資產頁面提供有關資源、其拓撲（裝置及其連線）、效能圖表及相關資源表格的摘要資訊。疑難排解Fibre Channel問題時、每個連接埠資產的效能圖表都很實用、因為它會顯示所選主要貢獻者連接埠的流量。連接埠資產頁面也會在此圖表中顯示緩衝對緩衝信用度量和連接埠錯誤、Insight會針對每個度量顯示個別的效能圖表。
