---
permalink: howto/more-on-dashboard-variables.html 
sidebar: sidebar 
keywords:  
summary: 儀表板變數有多種類型、可用於不同欄位、而且必須遵循命名規則。以下將說明這些概念。 
---
= 儀表板變數的詳細資訊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儀表板變數有多種類型、可用於不同欄位、而且必須遵循命名規則。以下將說明這些概念。



== 可變類型

變數可以是下列其中一種類型：

*文字*：英數字元字串。這是預設的變數類型。

*數字*：數字或範圍。

*布林*：用於值為「真/假」、「是/否」、「0/1」等的欄位 對於布林變數、選項包括「_Yes_」、「_No_」、「_Non__」、「_any」。

*日期*：日期或日期範圍。



== 「'Generic'」變數

您可以按一下*變數*按鈕、然後選取上述其中一種類型、來設定一般或通用變數。這些類型一律顯示在下拉式清單頂端。此變數會被指定預設名稱、例如「$var1'」、且不會與特定的註釋或屬性相關聯。

設定一般變數可讓您在小工具中使用該變數來篩選該類型的_any欄位。例如、如果您有一個表格小工具顯示_Name_、_Alias_和_Vendor_（都是文字類型屬性）、而「$var1'」是文字類型的變數、則您可以在小工具中為每個欄位設定篩選條件、以使用$var1變數。您可以將其他小工具設定為使用$var1做為這些或任何文字欄位。

在儀表板頁面上、將$var1設為值（例如「'NetApp'」）將會篩選_all_小工具中設定為使用該變數的所有欄位。如此一來、您就能一次更新多個小工具、以突顯您隨意選擇的儀表板資料。

由於一般變數可用於該類型的任何欄位、因此您可以變更一般變數的名稱、而不需變更其功能。

[NOTE]
====
所有變數都會視為「一般」變數、即使是您針對特定屬性所建立的變數、因為當您為某種類型的任何屬性或註釋設定篩選器時、會顯示某種類型的所有已設定變數。不過、最佳實務做法是在您使用通用變數來篩選多個欄位的值時、建立通用變數、如上面的_Name/Alias/Vendor_範例所示。

====


== 可變命名

變數名稱：

* 必須始終以「$$」為前置詞。這會在您設定變數時自動新增。
* 不得包含任何特殊字元；僅允許使用字母A-Z和數字0-9。
* 不得超過20個字元、包括「'$'」符號。
* 不區分大小寫：$CityName和$cityname是相同的變數。
* 不能與現有的變數名稱相同。
* 不能只是「'$'」符號。




== 使用變數的小工具

變數可搭配下列小工具使用：

* 區域表
* 長條圖
* 方塊繪圖圖表
* 折線圖
* 散點圖
* 單一值Widget
* 不規則曲線圖
* 堆疊區域圖
* 表格小工具

