---
sidebar: sidebar 
permalink: task_config_telegraf_dcos.html 
keywords: telegraf, installation, install, dcos 
summary: Dcos組態 
---
= 資料中心/作業系統資料收集器
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
支援此資料收集器、可從資料中心/作業系統收集數據。Cloud Insights



== 安裝

. 從 * 可伺服 > 收集器 * 、按一下 * + 資料收集器 * 。選擇 *DC/OS* 。
+
如果您尚未設定收集的值機員、系統會提示您 link:task_config_telegraf_agent.html["安裝代理程式"] 在您的環境中。

+
如果您已設定代理程式、請選取適當的作業系統或平台、然後按一下*繼續*。

. 請依照「DC-OS組態」畫面中的指示來設定資料收集器。這些指示會因您用來收集資料的作業系統或平台類型而有所不同。




== 設定

如需設定資訊、請參閱 https://docs.mesosphere.com["資料中心/作業系統文件"]。



== 物件與計數器

收集下列物件及其計數器：

[cols="<.<,<.<,<.<,<.<"]
|===
| 物件 | 識別碼 | 屬性 | 資料點 


| dcos_nod | dcos_container
dcos_app | 叢集
主機名稱
路徑（僅限檔案系統欄位）
介面（僅限網路欄位）
conter_id
task_name | system_uptime （浮動）
CPU_核心 （浮動）
CPU_total （浮動）
CPU_user （浮動）
CPU_SYSTEM （浮動）
CPU_ 閒置（浮動）
CPU_WAIT （浮動）
load_1 分鐘（浮動）
負載 _ 5 分鐘（浮動）
load_15 分鐘（浮動）
filesystem_capimal_bytes （ int ）
filesystem_capimal_USed_bytes （ int ）
filesystem_capimal_free 位元組（ int ）
filesystem_inode_total （浮動）
filesystem_inode_used （浮點型）
filesystem_inode_free （浮動）
memory_total_bytes （ int ）
memory_free 位元組（ int ）
memory_buffer_bytes （ int ）
memory_netapped_bytes （ int ）
swap_total_bytes （ int ）
swap_free 位元組（ int ）
swap_used 位元組（ int ）
network_in_bytes （ int ）
network_Out_bytes （ int ）
network_in_packets （浮動）
network_Out_packets （浮動）
NETWORD_IN_DOUBLE （浮動）
NETWORD_OUT 捨棄（浮動）
NETWORD_IN_errors （浮動）
NETWORD_Out_errors （浮點型）
處理序數（浮動） 
|===


== 疑難排解

如需其他資訊、請參閱 link:concept_requesting_support.html["支援"] 頁面。
