---
sidebar: sidebar 
permalink: telegraf_agent_k8s_config_options.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s, options, configuration 
summary: NetApp Kubernetes 監控營運者有許多可設定的選項。 
---
= NetApp Kubernetes 監控營運者組態選項
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
。 link:task_config_telegraf_agent_k8s.html["NetApp Kubernetes監控操作員"] 您可以自訂安裝與組態。

下表列出 AgentConfiguration 檔案的可能選項：

[cols="1,1,2"]
|===
| 元件 | 選項 | 說明 


| 代理程式 |  | 操作員可以安裝的所有元件通用的組態選項。這些選項可視為「整體」選項。 


|  | dockerRepo | 相較於 Cloud Insights 泊塢視窗 repo 、 dockerRepo 會置換以從客戶的「私有」泊塢視窗資源中拉出影像。預設為 Cloud Insights 泊塢視窗 repo 


|  | dockerImagePullSecret | 選用：客戶的秘密私人回購 


|  | 叢集名稱 | 可唯一識別所有客戶叢集的任意文字欄位。這在 Cloud Insights 租戶中應該是唯一的。預設是客戶在 UI 中輸入的「叢集名稱」欄位 


|  | Proxy
格式：
Proxy ：
  伺服器：
  連接埠：
  使用者名稱：
  密碼：
  NoProxy ：
  啟用 ISTelegrafProxy: 
  已啟用的 isAuProxy: 
  已啟用 isFluentbitProxy: 
  啟用的 isCollectorProxy: | 客戶可選擇設定 Proxy 。這通常是客戶的公司代理。 


| Telegraf |  | 可自訂電信業者安裝的組態選項 


|  | CollectionInterval | 度量收集時間間隔（以秒為單位）（最大 = 60 秒） 


|  | dsCpuLimit | Telegraf DS 的 CPU 限制 


|  | dsMemLimit | Telegraf DS 的記憶體限制 


|  | dsCpuRequest | 對 Telegraf DS 的 CPU 要求 


|  | dsMemRequest | 對 Telegraf DS 的記憶體要求 


|  | rsCpuLimit | Telegraf RS 的 CPU 限制 


|  | rsMemLimit | Telegraf RS 的記憶體限制 


|  | rsCpuRequest | 適用於 Telegraf RS 的 CPU 要求 


|  | rsMemRequest | 對 Telegraf RS 的記憶體要求 


|  | dockerMountPoint | dockerMountPoint 路徑的置換。這適用於在 k8s 平台（例如 Cloud Foundry ）上安裝非標準泊塢視窗 


|  | dockerUnixSocket | dockerUnixSocket 路徑的置換。這適用於在 k8s 平台（例如 Cloud Foundry ）上安裝非標準泊塢視窗。 


|  | CrioSockPath | crioSockPath 路徑的置換。這適用於在 k8s 平台（例如 Cloud Foundry ）上安裝非標準泊塢視窗。 


|  | RunPrivileged | 以特殊權限模式執行 Telegraf 容器。如果您的 k8s 節點上已啟用 SELinux 、請將此設定為 True 


|  | 批次大小 | 請參閱 link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf 組態文件"] 


|  | bufferLimit | 請參閱 link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf 組態文件"] 


|  | 圓週期間隔 | 請參閱 link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf 組態文件"] 


|  | CollectionJitter | 請參閱 link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf 組態文件"] 


|  | 精度 | 請參閱 link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf 組態文件"] 


|  | FlushInterval | 請參閱 link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf 組態文件"] 


|  | FlushJitter | 請參閱 link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf 組態文件"] 


|  | 輸出逾時 | 請參閱 link:https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent["Telegraf 組態文件"] 


|  | 啟用 DockerMetricCollection | 收集 Docker 指標。根據預設、此值會設為 true 、並會針對內部部署、泊塢視窗型的 k8s 部署收集泊塢視窗度量。若要停用泊塢視窗度量集合、請將此設定為假。 


|  | dsTolerations | Telegraf-DS 額外的容忍度。 


|  | RsTolerations | Telegraf-RS 額外容忍度。 


| Kube-state 指標 |  | 可自訂操作員的 kbe 狀態度量安裝的組態選項 


|  | cpuLimit | kube 狀態度量部署的 CPU 限制 


|  | MemLimit | kube 狀態度量部署的記憶體限制 


|  | cpuRequest | CPU 要求進行 kube 狀態指標部署 


|  | MemRequest | kube 狀態指標部署的記憶體要求 


|  | 資源 | 以逗號分隔的資源清單、可供擷取。
範例： cronjobs 、 daemonsets 、部署、擷取、工作、命名空間、節點、持續不斷的 voleclaims 、
持續磁碟區、 Pod 、複製集、資源等量、服務、狀態集 


|  | 公差 | Kube-state - 衡量其他容忍度。 


|  | 標籤 | kube 狀態度量應擷取的資源清單（以逗號分隔）

++
範例： cronjobs=[*],daemonsets=[*],targets=[*],jobs=[*],命名 空間 =[*],nodes=[*],
永久卷冊 =[*] 、持續卷 =[*] 、 Pod =[*] 、複製集 =[*] 、資源 equotas=[*] 、服務 =[*] 、狀態集 =[*]
++ 


| 記錄 |  | 可自訂記錄收集和安裝操作員的組態選項 


|  | readFromHead | 是非題、應能流暢地從標頭讀取記錄 


|  | 逾時 | 逾時、以秒為單位 


|  | dnsMode | TCP/UDP 、 DNS 模式 


|  | 流暢的位元容忍度 | Fluent-bit-DS 額外公差。 


|  | 事件導出者容忍度 | 事件導出者額外容忍度。 


| 工作負載對應 |  | 可自訂工作負載對應集合及安裝 Operator 的組態選項 


|  | cpuLimit | Net 觀察者 DS 的 CPU 上限 


|  | MemLimit | net 觀察者 DS 的記憶體限制 


|  | cpuRequest | CPU 要求取得 Net 觀察者 DS 


|  | MemRequest | net 觀察者 DS 的記憶體要求 


|  | MetricAggergationInterval. | 度量集合時間間隔（以秒為單位） 


|  | bpfPollInterval. | BPF 輪詢時間間隔（秒） 


|  | enabledDNSookup | 是非題、啟用 DNS 查詢 


|  | L4-公差 | net-觀察者 -L4-DS 額外容忍度。 
|===


== AgentConfiguration 檔案範例

以下是 AgentConfiguration 檔案範例。請注意、此處並未擷取所有選項：

[listing]
----
apiVersion: monitoring.netapp.com/v1alpha1
kind: AgentConfiguration
metadata:
  name: netapp-monitoring-configuration
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    installed-by: nkmo-NAMESPACE_PLACEHOLDER

spec:
  agent:
    # a uniquely identifiable user friendly clustername. This clustername should be unique across
    # all clusters in your cloud insights tenant
    clusterName: pbhat-dev

    # optional: proxy settings. This is usually your corporate proxy settings
    proxy:
      server: testserver
      port: 3128
      noproxy: websock.svc
      username: user
      password: pass
      isTelegrafProxyEnabled: true
      isFluentbitProxyEnabled: true
      isCollectorsProxyEnabled: true
      isAuProxyEnabled: false

    # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry
    # Please see documentation link here:
    dockerRepo: dummy.docker.repo/long/path/to/test
    # Optional: A docker image pull secret that maybe needed for your private docker registry
    dockerImagePullSecret: docker-secret-name

    # Set runPrivileged to true SELinux is enabled on your kubernetes nodes
    # runPrivileged: false

  telegraf:
    # use these settings to fine tune data collection
    collectionInterval: 20s

    # batchSize:
    # bufferLimit:
    # roundInterval:
    # collectionJitter:
    # precision:
    # flushInterval:
    # flushJitter:

    # Collect kubernetes.system_container metrics and objects in the kube-system|cattle-system namespaces for managed kubernetes clusters
    # (EKS, AKS, GKE, managed Rancher). Set this to true if you want collect these metrics.
    #managedK8sSystemMetricCollectionEnabled: true|false

    # Collect kubernetes.pod_volume (pod ephemeral storage) metrics. Set this to true if you want to collect these metrics.
    #podVolumeMetricFilteringEnabled: true|false

    # Declare Rancher cluster as managed. Set this to true if your Rancher cluster is managed as opposed to on-premise.
    #isManagedRancher: true|false

    # By default, docker metrics will be collected for on-premise, docker-based k8s deployments. To disable docker metric collection, set this to false.
    # dockerMetricCollectionEnabled: true|false


    # Deamonset CPU/Mem limits and requests
    # dsCpuLimit:
    # dsMemLimit:
    # dsCpuRequest:
    # dsMemRequest:

    # Replicaset CPU/Mem limits and requests
    # rsCpuLimit:
    # rsMemLimit:
    # rsCpuRequest:
    # rsMemRequest:

  kube-state-metrics:
    # cpuLimit:
    # memLimit:
    # cpuRequest:
    # memRequest:

    # a comma separated list of resources to capture.
    # example: cronjobs,daemonsets,deployments,ingresses,jobs,namespaces,nodes,persistentvolumeclaims,persistentvolumes,pods,replicasets,resourcequotas,services,statefulsets
    # resources:

    # a comma seperated list of resources that kube-state-metrics should capture
    # example: cronjobs=[*],daemonsets=[*],deployments=[*],ingresses=[*],jobs=[*],namespaces=[*],nodes=[*],persistentvolumeclaims=[*],persistentvolumes=[*],pods=[*],replicasets=[*],resourcequotas=[*],services=[*],statefulsets=[*]
    # labels:
----